### ISSUE TITLE
yarn-per 提交报错

### ISSUE THREAD

**Issue by YinChunGuang** [DTStack/flinkStreamSQL#101]
[datamart@niwodai5 ~]$ cd kunpengStreamSQL/
[datamart@niwodai5 kunpengStreamSQL]$ ls
bin  examples  FlinkExample-1.0-SNAPSHOT.jar  lib  plugins  sql.core-1.0-SNAPSHOT.jar
[datamart@niwodai5 kunpengStreamSQL]$ cd bin/
[datamart@niwodai5 bin]$ ls
submit.bat  submit.sh  submit.sh0  testsubmit.sh
[datamart@niwodai5 bin]$  sh submit.sh  -yarnconf  /etc/hadoop/conf  -remoteSqlPluginPath  /home/datamart/kunpengStreamSQL/plugins  -sql ../examples/kafka2console.sql  -flinkconf /home/datamart/flink-1.7.1/conf/  -mode yarnPer  -flinkJarPath  /home/datamart/flink-1.7.1/lib
sql submit application name :FLINK-JOB:4885e380-cbb1-41b9-b245-d3ea0bd27854
[datamart@niwodai5 bin]$ SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
----init yarn success ----
deploy per_job with appId: application_1554984152144_0560, jobId: 32dd7835fd51a65b66a95f35389799ea
---submit end----

[datamart@niwodai5 bin]$ 
[datamart@niwodai5 bin]$ 
[datamart@niwodai5 bin]$ ls   /home/datamart/kunpengStreamSQL/plugins
consolesink  elasticsearchsink  hbaseasyncside  kafka08sink  kafka09source  kafka10source  kafka11source  mongoasyncside  mysqlallside    `mysqlsink`      oracleasyncside  redisallside    redissink
core.jar     hbaseallside       hbasesink       kafka09sink  kafka10sink    kafka11sink    mongoallside   mongosink       mysqlasyncside  oracleallside  oraclesink       redisasyncside  serversocketsource
[datamart@niwodai5 bin]$ ls /home/datamart/kunpengStreamSQL/plugins/kafka10source/kafka10-source.jar
/home/datamart/kunpengStreamSQL/plugins/kafka10source/kafka10-source.jar
[datamart@niwodai5 bin]$ 

![flink1](https://user-images.githubusercontent.com/11421720/56274237-fb108880-6130-11e9-93f2-f57e50ddbd93.png)
![flink3](https://user-images.githubusercontent.com/11421720/56274255-019f0000-6131-11e9-9cca-47ea593f5feb.png)

**Comment by yangsishu** [comment]
这些插件包所有的计算节点都要放一份的

**Comment by YinChunGuang** [comment]
hi，是的，所有的节点都放置了

**Comment by YinChunGuang** [comment]
![flink4](https://user-images.githubusercontent.com/11421720/56331380-8e43cf80-61be-11e9-9d14-3004ea73fd20.png)
在每一个节点上都放置了这个问对应的plugin了

**Comment by yangsishu** [comment]
用的是那个分支

**Comment by YinChunGuang** [comment]
1.7_dev

**Comment by AccordwangAccord** [comment]
@YinChunGuang @yangsishu 两位大佬这个问题搞定了吗？我也遇到过类似的问题了
！麻烦两位大佬告知下

**Comment by dengli2016** [comment]
> ![flink4](https://user-images.githubusercontent.com/11421720/56331380-8e43cf80-61be-11e9-9d14-3004ea73fd20.png)
> 在每一个节点上都放置了这个问对应的plugin了

求教一下有没有碰到这样的问题呢，烦请帮忙解答
![image](https://user-images.githubusercontent.com/16996567/57977651-6f3f9400-7a2f-11e9-87e4-42ce848e035c.png)

**Comment by ZSS2** [comment]
ClassLoader info: URL ClassLoader:
    file: '/app/hadoop/share/hadoop/yarn/lib/plugins/kafka11sink/kafka11-sink.jar' (missing)
    file: '/app/hadoop/share/hadoop/yarn/lib/plugins/kafka11source/kafka11-source.jar' (missing)
Class not resolvable through given classloader.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:236)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:104)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:267)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:704)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.dtstack.flink.sql.source.kafka.consumer.CustomerJsonConsumer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:129)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:78)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:566)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:552)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:540)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:501)
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:224)
	... 4 more
测试环境没出问题，生产环境出问题。结果放入flink集群的所有节点也出现这个问题，请问同问这个问题的解决了吗？

**Comment by ZSS2** [comment]
问题已解决；提交任务出现拉去路径插件jar包出现问题可能存在原因：
1、所需要的插件jar需放在flink集群的所有节点
2、部署yarn集群环境，所需插件jar包需要存放到所有的nodemanager上
3、yarn集群环境下可能存在不同的queue，拉去不到路径下的插件jar包可能你的queue需要指定同时可能还要考虑提交任务的用户是否会有影响

目前根据上述操作，本人问题已经解决！！！
PS：本人使用的是1.7_dev分支，queue可能存在问题，本人根据需要修改了代码；其他使用者注意

**Comment by baochengjie** [comment]
@2019NewStar 能问一下你具体是怎么解决的吗

**Comment by qiuqingyu** [comment]
> 问题已解决；提交任务出现拉去路径插件jar包出现问题可能存在原因：
> 1、所需要的插件jar需放在flink集群的所有节点
> 2、部署yarn集群环境，所需插件jar包需要存放到所有的nodemanager上
> 3、yarn集群环境下可能存在不同的queue，拉去不到路径下的插件jar包可能你的queue需要指定同时可能还要考虑提交任务的用户是否会有影响
> 
> 目前根据上述操作，本人问题已经解决！！！
> PS：本人使用的是1.7_dev分支，queue可能存在问题，本人根据需要修改了代码；其他使用者注意

麻烦问下如何解决的？

**Comment by qiuqingyu** [comment]
> > ![flink4](https://user-images.githubusercontent.com/11421720/56331380-8e43cf80-61be-11e9-9d14-3004ea73fd20.png)
> > 在每一个节点上都放置了这个问对应的plugin了
> 
> 求教一下有没有碰到这样的问题呢，烦请帮忙解答
> ![image](https://user-images.githubusercontent.com/16996567/57977651-6f3f9400-7a2f-11e9-87e4-42ce848e035c.png)

麻烦问下是否解决了呢？
