### ISSUE TITLE
在yarn模式下运行，报org.apache.flink.table.runtime.CRowKeySelector错误

### ISSUE THREAD

**Issue by jinshuangxian** [DTStack/flinkStreamSQL#102]
local方式运行正常，
在yarn模式下运行，报下面的错误：
2019-04-19 13:53:51,046 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Source: tomcat_access_raw_log -> Map -> to: Row -> from: (message, outip, PROCTIME) -> where: (IS NOT NULL(outip)), select: (outip, PROCTIME) (1/1) (59e977b24cb2fa585bad9989982472a3) switched from DEPLOYING to FAILED.
org.apache.flink.streaming.runtime.tasks.StreamTaskException: Could not instantiate outputs in order.
        at org.apache.flink.streaming.api.graph.StreamConfig.getOutEdgesInOrder(StreamConfig.java:398)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.createStreamRecordWriters(StreamTask.java:1164)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.<init>(StreamTask.java:212)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.<init>(StreamTask.java:190)
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.<init>(SourceStreamTask.java:51)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.flink.runtime.taskmanager.Task.loadAndInstantiateInvokable(Task.java:1444)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:688)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.table.runtime.CRowKeySelector
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:120)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:76)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1868)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:433)
        at java.util.ArrayList.readObject(ArrayList.java:797)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1158)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)

**Comment by jinshuangxian** [comment]
使用的是flink是1.6.2版本，flinkStreamSql1.6.2

**Comment by jinshuangxian** [comment]
在flink集群每台机器flink的lib目录下放flink-table_2.11-1.6.2.jar，然后重启yarn-session.sh。然后问题解决。

**Comment by YinChunGuang** [comment]
兄弟，submit  的提交参数截图给看看吧，我也是flink on yarn 和yarnPer  方式提交都是plugin 加载不到。
感谢！

**Comment by gcstar** [comment]
可以把core包打成fat jar

**Comment by maidou75293** [comment]
我也遇到加载不了 plugin问题 ，你们咱们处理的

**Comment by maidou75293** [comment]
> 可以把core包打成fat jar

翻遍加一下微信么， 我们自己组建个微信群吧
