### ISSUE TITLE
HBase sink

### ISSUE THREAD

**Issue by lixiyuan123** [DTStack/flinkStreamSQL#116]
大神们好，HBase sink 无法写数据？

**Comment by yangsishu** [comment]
有报错之类的就把错误信息贴出来

**Comment by lixiyuan123** [comment]
> 有报错之类的就把错误信息贴出来

谢谢您的回答。我使用的是1.6版本。然后报了如下的错：
使用hbase-sink模块时抛出如下异常：
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: class org.apache.hadoop.yarn.client.ConfiguredRMFailoverProxyProvider not org.apache.hadoop.yarn.client.RMFailoverProxyProvider
at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:1927)
at org.apache.hadoop.yarn.client.RMProxy.createRMFailoverProxyProvider(RMProxy.java:154)
at org.apache.hadoop.yarn.client.RMProxy.createRMProxy(RMProxy.java:87)
at org.apache.hadoop.yarn.client.ClientRMProxy.createRMProxy(ClientRMProxy.java:70)
at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.serviceStart(YarnClientImpl.java:139)
at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
at com.dtstack.flink.sql.launcher.perjob.PerJobClusterClientBuilder.init(PerJobClusterClientBuilder.java:60)
at com.dtstack.flink.sql.launcher.perjob.PerJobSubmitter.submit(PerJobSubmitter.java:53)
at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:83)

不过前面我看到也有朋友发了类似的issues，@oOKevinOo  这个为朋友。我按照他的提示。已经不报这个错了。
谢谢。

**Comment by lycbug666** [comment]
> > 有报错之类的就把错误信息贴出来
> 
> 谢谢您的回答。我使用的是1.6版本。然后报了如下的错：
> 使用hbase-sink模块时抛出如下异常：
> Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: class org.apache.hadoop.yarn.client.ConfiguredRMFailoverProxyProvider not org.apache.hadoop.yarn.client.RMFailoverProxyProvider
> at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:1927)
> at org.apache.hadoop.yarn.client.RMProxy.createRMFailoverProxyProvider(RMProxy.java:154)
> at org.apache.hadoop.yarn.client.RMProxy.createRMProxy(RMProxy.java:87)
> at org.apache.hadoop.yarn.client.ClientRMProxy.createRMProxy(ClientRMProxy.java:70)
> at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.serviceStart(YarnClientImpl.java:139)
> at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
> at com.dtstack.flink.sql.launcher.perjob.PerJobClusterClientBuilder.init(PerJobClusterClientBuilder.java:60)
> at com.dtstack.flink.sql.launcher.perjob.PerJobSubmitter.submit(PerJobSubmitter.java:53)
> at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:83)
> 
> 不过前面我看到也有朋友发了类似的issues，@oOKevinOo 这个为朋友。我按照他的提示。已经不报这个错了。
> 谢谢。

请问具体是怎么 解决的呢？

**Comment by hupper0** [comment]
解决方案呢，可以发出来吗，我也遇到了
