### ISSUE TITLE
elasticsearch有权限认证

### ISSUE THREAD

**Issue by gangly** [DTStack/flinkStreamSQL#125]
大神们好，
目前elasticsearch有权限认证，
即需要账号密码，目前支持吗
如何在建表的时候配置，
谢谢

**Comment by 2019NewStar** [comment]
@gangly  请教一下，如果Kafka数据写ES，ES的id你有测试是否可以支持动态生成吗？
ES的type和index是需要提前创建的吗？如何index支持动态创建？

**Comment by yangsishu** [comment]
现在不支持权限的配置

**Comment by yangsishu** [comment]
写入es的时候默认会生成唯一id，_id这个属性

**Comment by gangly** [comment]
> 现在不支持权限的配置

配置了es，运行报如下错误，请问是什么问题？

`java.lang.RuntimeException: Elasticsearch client is not connected to any Elasticsearch nodes!
        at org.apache.flink.streaming.connectors.elasticsearch5.Elasticsearch5ApiCallBridge.createClient(Elasticsearch5ApiCallBridge.java:82)
        at org.apache.flink.streaming.connectors.elasticsearch.ElasticsearchSinkBase.open(ElasticsearchSinkBase.java:287)
        at com.dtstack.flink.sql.sink.elasticsearch.MetricElasticsearchSink.open(MetricElasticsearchSink.java:49)
        at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
        at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
        at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:420)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:296)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:712)
        at java.lang.Thread.run(Thread.java:748)

05/30/2019 11:08:34     Job execution switched to status FAILING.
`

**Comment by gangly** [comment]
> 现在不支持权限的配置
@yangsishu 
配置了es，无权限的，es版本5.6.14，运行报如下错误，请问是什么问题？
`java.lang.RuntimeException: Elasticsearch client is not connected to any Elasticsearch nodes!
at org.apache.flink.streaming.connectors.elasticsearch5.Elasticsearch5ApiCallBridge.createClient(Elasticsearch5ApiCallBridge.java:82)
at org.apache.flink.streaming.connectors.elasticsearch.ElasticsearchSinkBase.open(ElasticsearchSinkBase.java:287)
at com.dtstack.flink.sql.sink.elasticsearch.MetricElasticsearchSink.open(MetricElasticsearchSink.java:49)
at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:420)
at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:296)
at org.apache.flink.runtime.taskmanager.Task.run(Task.java:712)
at java.lang.Thread.run(Thread.java:748)
05/30/2019 11:08:34 Job execution switched to status FAILING.
`

**Comment by gangly** [comment]
能写入到es5,  问题解决

**Comment by 2019NewStar** [comment]
> > 现在不支持权限的配置
> > @yangsishu
> > 配置了es，无权限的，es版本5.6.14，运行报如下错误，请问是什么问题？
> > `java.lang.RuntimeException: Elasticsearch client is not connected to any Elasticsearch nodes! at org.apache.flink.streaming.connectors.elasticsearch5.Elasticsearch5ApiCallBridge.createClient(Elasticsearch5ApiCallBridge.java:82) at org.apache.flink.streaming.connectors.elasticsearch.ElasticsearchSinkBase.open(ElasticsearchSinkBase.java:287) at com.dtstack.flink.sql.sink.elasticsearch.MetricElasticsearchSink.open(MetricElasticsearchSink.java:49) at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36) at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102) at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48) at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:420) at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:296) at org.apache.flink.runtime.taskmanager.Task.run(Task.java:712) at java.lang.Thread.run(Thread.java:748) 05/30/2019 11:08:34 Job execution switched to status FAILING. `

异常怎么解决的？

**Comment by AccordwangAccord** [comment]
@gangly 请问一下你们用的string类型 不是keyword吗？比如
CREATE TABLE elasticsearch_type(
    testid keyword ,
    user_type integer,
    in_shop_cnt long
 )WITH(
    type ='elasticsearch',
    address ='xxxx:9200',
    cluster='es-test-cluster',
    estype ='elasticsearch_type',
    index ='test01',
    id ='0',
    parallelism ='1'
 );

**Comment by lixiaolevae** [comment]
> 能写入到es5, 问题解决

怎么解决的

**Comment by a49a** [comment]
使用FlinkX 1.12版本试试
