### ISSUE TITLE
yarn-pre模式提交任务，能否指定hdfs中的plugin路径？

### ISSUE THREAD

**Issue by lycbug666** [DTStack/flinkStreamSQL#126]
目前flink任务在yarn集群中运行，如果直接使用本项目，需要在每台nodemanager的相同位置部署plugin目录。
请问是否能将plugins放置在hdfs中，避免机器扩缩容时忘记操作？
如果不可以，应该采用何种方式修改？
谢谢解答。

**Comment by yangsishu** [comment]
这个现在不支持

**Comment by lycbug666** [comment]
> 这个现在不支持

采用 flink 自带的 run 方法，直接将 Main.main 作为主函数运行，使用 -yt 添加 plugins 文件夹，可以将 plugins 文件夹内的所有 jar 传入yanr nodemanager 的 classpath 中，目前解决了这个问题。

`flink run -m yarn-cluster -d -yqu root.default -ynm mysql-side-join-test -yn 2 -ytm 2048 -ys 2 -yt /app/rtc_flink/flink-sql-mod/plugins   -c com.dtstack.flink.sql.Main /app/rtc_flink/flink-sql-mod/core-v1.5.4.jar -sql "CREATE TABLE MyTable ( name varchar, channel varchar, pv INT )WITH( type = 'kafka10', bootstrapServers = '192.168.10.4:9092', zookeeperQuorum = '192.168.10.4:2181', offsetReset = 'latest',      topic = 'mysql-stream', parallelism = '1'  ); CREATE TABLE sideTable( channel varchar, info varchar,     PRIMARY KEY(channel), PERIOD FOR SYSTEM_TIME )WITH( type ='mysql',  url ='jdbc:mysql://192.168.10.4:3306/test?charset=utf8',     userName ='root',     password ='123456',     tableName ='sideTable',     cache ='LRU',     cacheSize ='10000',     cacheTTLMs ='60000',     partitionedJoin='false',     parallelism ='1'  );CREATE TABLE MyResult(     name varchar,     channel varchar,     info  varchar  )WITH(     type ='mysql',     url ='jdbc:mysql://192.168.10.4:3306/test?charset=utf8',     userName ='root',     password ='123456',     tableName ='MyResult',     parallelism ='1'  ); insert into MyResult select d.name, d.channel, d.info from ( select a.*,b.info from MyTable a join sideTable b on a.channel=b.channel ) as d;" -name mysql-side-join-test -remoteSqlPluginPath /app/rtc_flink/flink-sql-mod/plugins -localSqlPluginPath /app/rtc_flink/flink-sql-mod/plugins -mode yarnPer  -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\}`

**Comment by qiuqingyu** [comment]
> > 这个现在不支持
> 
> 采用 flink 自带的 run 方法，直接将 Main.main 作为主函数运行，使用 -yt 添加 plugins 文件夹，可以将 plugins 文件夹内的所有 jar 传入yanr nodemanager 的 classpath 中，目前解决了这个问题。
> 
> `flink run -m yarn-cluster -d -yqu root.default -ynm mysql-side-join-test -yn 2 -ytm 2048 -ys 2 -yt /app/rtc_flink/flink-sql-mod/plugins -c com.dtstack.flink.sql.Main /app/rtc_flink/flink-sql-mod/core-v1.5.4.jar -sql "CREATE TABLE MyTable ( name varchar, channel varchar, pv INT )WITH( type = 'kafka10', bootstrapServers = '192.168.10.4:9092', zookeeperQuorum = '192.168.10.4:2181', offsetReset = 'latest', topic = 'mysql-stream', parallelism = '1' ); CREATE TABLE sideTable( channel varchar, info varchar, PRIMARY KEY(channel), PERIOD FOR SYSTEM_TIME )WITH( type ='mysql', url ='jdbc:mysql://192.168.10.4:3306/test?charset=utf8', userName ='root', password ='123456', tableName ='sideTable', cache ='LRU', cacheSize ='10000', cacheTTLMs ='60000', partitionedJoin='false', parallelism ='1' );CREATE TABLE MyResult( name varchar, channel varchar, info varchar )WITH( type ='mysql', url ='jdbc:mysql://192.168.10.4:3306/test?charset=utf8', userName ='root', password ='123456', tableName ='MyResult', parallelism ='1' ); insert into MyResult select d.name, d.channel, d.info from ( select a.*,b.info from MyTable a join sideTable b on a.channel=b.channel ) as d;" -name mysql-side-join-test -remoteSqlPluginPath /app/rtc_flink/flink-sql-mod/plugins -localSqlPluginPath /app/rtc_flink/flink-sql-mod/plugins -mode yarnPer -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\}`

为什么我按照你说的方法运行的时候一直在报错
Caused by: java.lang.ClassNotFoundException: org.apache.flink.table.api.TableEnvironment
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
请问是否遇到了这种问题？

**Comment by lycbug666** [comment]
> > > 这个现在不支持
> > 
> > 
> > 采用 flink 自带的 run 方法，直接将 Main.main 作为主函数运行，使用 -yt 添加 plugins 文件夹，可以将 plugins 文件夹内的所有 jar 传入yanr nodemanager 的 classpath 中，目前解决了这个问题。
> > `flink run -m yarn-cluster -d -yqu root.default -ynm mysql-side-join-test -yn 2 -ytm 2048 -ys 2 -yt /app/rtc_flink/flink-sql-mod/plugins -c com.dtstack.flink.sql.Main /app/rtc_flink/flink-sql-mod/core-v1.5.4.jar -sql "CREATE TABLE MyTable ( name varchar, channel varchar, pv INT )WITH( type = 'kafka10', bootstrapServers = '192.168.10.4:9092', zookeeperQuorum = '192.168.10.4:2181', offsetReset = 'latest', topic = 'mysql-stream', parallelism = '1' ); CREATE TABLE sideTable( channel varchar, info varchar, PRIMARY KEY(channel), PERIOD FOR SYSTEM_TIME )WITH( type ='mysql', url ='jdbc:mysql://192.168.10.4:3306/test?charset=utf8', userName ='root', password ='123456', tableName ='sideTable', cache ='LRU', cacheSize ='10000', cacheTTLMs ='60000', partitionedJoin='false', parallelism ='1' );CREATE TABLE MyResult( name varchar, channel varchar, info varchar )WITH( type ='mysql', url ='jdbc:mysql://192.168.10.4:3306/test?charset=utf8', userName ='root', password ='123456', tableName ='MyResult', parallelism ='1' ); insert into MyResult select d.name, d.channel, d.info from ( select a.*,b.info from MyTable a join sideTable b on a.channel=b.channel ) as d;" -name mysql-side-join-test -remoteSqlPluginPath /app/rtc_flink/flink-sql-mod/plugins -localSqlPluginPath /app/rtc_flink/flink-sql-mod/plugins -mode yarnPer -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\}`
> 
> 为什么我按照你说的方法运行的时候一直在报错
> Caused by: java.lang.ClassNotFoundException: org.apache.flink.table.api.TableEnvironment
> at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> ... 26 more
> 请问是否遇到了这种问题？

@qiuqingyu 需要将 flink-table.jar 置入 flink/lib 目录中

**Comment by qiuqingyu** [comment]
> > > > 这个现在不支持
> > > 
> > > 
> > > 采用 flink 自带的 run 方法，直接将 Main.main 作为主函数运行，使用 -yt 添加 plugins 文件夹，可以将 plugins 文件夹内的所有 jar 传入yanr nodemanager 的 classpath 中，目前解决了这个问题。
> > > `flink run -m yarn-cluster -d -yqu root.default -ynm mysql-side-join-test -yn 2 -ytm 2048 -ys 2 -yt /app/rtc_flink/flink-sql-mod/plugins -c com.dtstack.flink.sql.Main /app/rtc_flink/flink-sql-mod/core-v1.5.4.jar -sql "CREATE TABLE MyTable ( name varchar, channel varchar, pv INT )WITH( type = 'kafka10', bootstrapServers = '192.168.10.4:9092', zookeeperQuorum = '192.168.10.4:2181', offsetReset = 'latest', topic = 'mysql-stream', parallelism = '1' ); CREATE TABLE sideTable( channel varchar, info varchar, PRIMARY KEY(channel), PERIOD FOR SYSTEM_TIME )WITH( type ='mysql', url ='jdbc:mysql://192.168.10.4:3306/test?charset=utf8', userName ='root', password ='123456', tableName ='sideTable', cache ='LRU', cacheSize ='10000', cacheTTLMs ='60000', partitionedJoin='false', parallelism ='1' );CREATE TABLE MyResult( name varchar, channel varchar, info varchar )WITH( type ='mysql', url ='jdbc:mysql://192.168.10.4:3306/test?charset=utf8', userName ='root', password ='123456', tableName ='MyResult', parallelism ='1' ); insert into MyResult select d.name, d.channel, d.info from ( select a.*,b.info from MyTable a join sideTable b on a.channel=b.channel ) as d;" -name mysql-side-join-test -remoteSqlPluginPath /app/rtc_flink/flink-sql-mod/plugins -localSqlPluginPath /app/rtc_flink/flink-sql-mod/plugins -mode yarnPer -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\}`
> > 
> > 
> > 为什么我按照你说的方法运行的时候一直在报错
> > Caused by: java.lang.ClassNotFoundException: org.apache.flink.table.api.TableEnvironment
> > at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> > at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> > at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> > ... 26 more
> > 请问是否遇到了这种问题？
> 
> @qiuqingyu 需要将 flink-table.jar 置入 flink/lib 目录中

您好，我按照您说的将flink-table.jar 放入 flink/lib 中，但是现在又报错：
org.apache.flink.client.program.ProgramInvocationException: The program caused an error: 
	at org.apache.flink.client.program.OptimizerPlanEnvironment.getOptimizedPlan(OptimizerPlanEnvironment.java:93)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:80)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:122)
	at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:235)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:213)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1050)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$11(CliFrontend.java:1126)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1924)
	at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1126)
Caused by: java.lang.NoSuchMethodError: scala.util.parsing.combinator.Parsers.$init$(Lscala/util/parsing/combinator/Parsers;)V
	at org.apache.flink.table.expressions.ExpressionParser$.<init>(ExpressionParser.scala:40)
	at org.apache.flink.table.expressions.ExpressionParser$.<clinit>(ExpressionParser.scala)
	at org.apache.flink.table.api.java.StreamTableEnvironment.fromDataStream(StreamTableEnvironment.scala:86)
	at com.dtstack.flink.sql.source.kafka.KafkaSource.genStreamSource(KafkaSource.java:120)
	at com.dtstack.flink.sql.source.kafka.KafkaSource.genStreamSource(KafkaSource.java:51)
	at com.dtstack.flink.sql.source.StreamSourceFactory.getStreamSource(StreamSourceFactory.java:90)
	at com.dtstack.flink.sql.Main.registerTable(Main.java:253)
	at com.dtstack.flink.sql.Main.main(Main.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:529)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:421)
	at org.apache.flink.client.program.OptimizerPlanEnvironment.getOptimizedPlan(OptimizerPlanEnvironment.java:83)
	... 11 more
我也将scala-libary放到了flink/lib目录下，但是仍然未解决该问题

**Comment by a49a** [comment]
使用FlinkX 1.12试试
