### ISSUE TITLE
流表join，分组报错

### ISSUE THREAD

**Issue by YinChunGuang** [DTStack/flinkStreamSQL#131]
CREATE TABLE k(
				lid decimal,
				mid decimal
			 ) WITH (
			 type ='kafka11', 
			 kafka.topic ='processExecuteResultOutputs',
			 parallelism ='1' 
			); 
			
CREATE TABLE o1( 
	lid decimal, 
	mid decimal ,
  primary key(lid,mid),
 PERIOD FOR SYSTEM_TIME 
 )WITH(
 type ='oracle',
 tableName = 'nwd.o1' ,
 cache = 'NONE', 
 parallelism ='1' 
); 
					
CREATE TABLE o2( 
	lid decimal, 
	mid decimal , 
  primary key(lid,mid),
 PERIOD FOR SYSTEM_TIME 
 )WITH(
 type ='oracle',
 url = 'jdbc:', 
 tableName = 'nwd.o2' ,
 cache = 'NONE', 
 parallelism ='1' 
); 
			 
CREATE TABLE o3( 
	lid decimal, 
	mid decimal, 
  primary key(lid,mid)
 )WITH(
 type ='oracle',
 url = 'jdbc:', 
 tableName = 'nwd.o3' ,
 cache = 'NONE', 
 parallelism ='1' 
); 		 
			
			
create temp ooo as 

	SELECT o2o.lid, tm1.mid
	FROM (
		SELECT o1o.lid AS lid, o1o.mid AS mid
		FROM k kk
			JOIN o1 o1o
			ON kk.mid = o1o.mid
				AND kk.lid = o1o.lid 
			GROUP BY o1o.mid,o1o.lid				
	 
) tm1
	LEFT JOIN o2 o2o
	ON tm1.mid = o2o.mid
		AND tm1.lid = o2o.lid
		;
			 
			 
insert into o3 select * from ooo;	

流表  join oracle 维度表， 分组的时候就报错

---exeSql---
SELECT o2o.lid, tm1.mid
FROM (SELECT o1o.lid AS lid, o1o.mid AS mid
FROM k AS kk
INNER JOIN o1 AS o1o ON kk.mid = o1o.mid AND kk.lid = o1o.lid
GROUP BY o1o.mid, o1o.lid) AS tm1
LEFT JOIN o2 AS o2o ON tm1.mid = o2o.mid AND tm1.lid = o2o.lid
---------side_exe_sql-----
select lid,mid from nwd.o1 where mid=?  and lid=? 
-----------------
Exception in thread "main" org.apache.flink.table.api.TableException: Table is not an append-only table. Use the toRetractStream() in order to handle add and retract messages.
	at org.apache.flink.table.api.StreamTableEnvironment.translate(StreamTableEnvironment.scala:888)
	at org.apache.flink.table.api.StreamTableEnvironment.translate(StreamTableEnvironment.scala:864)
	at org.apache.flink.table.api.java.StreamTableEnvironment.toAppendStream(StreamTableEnvironment.scala:199)
	at org.apache.flink.table.api.java.StreamTableEnvironment.toAppendStream(StreamTableEnvironment.scala:153)
	at com.dtstack.flink.sql.side.SideSqlExec.joinFun(SideSqlExec.java:614)
	at com.dtstack.flink.sql.side.SideSqlExec.registerTmpTable(SideSqlExec.java:565)
	at com.dtstack.flink.sql.side.LancherMainTest.main(LancherMainTest.java:172)

**Comment by zoudaokoulife** [comment]
我们内部先修复下，测试过了会推上来的

**Comment by todd5167** [comment]
master分支已经解决  @YinChunGuang
