### ISSUE TITLE
join 没有as 表名 的时候报错

### ISSUE THREAD

**Issue by YinChunGuang** [DTStack/flinkStreamSQL#133]
create temp ooo as 

	SELECT o2o.lid, tm1.mid
	FROM (
		SELECT o1o.lid AS lid, o1o.mid AS mid
		FROM kk
			JOIN   o1o
			ON kk.mid = o1o.mid
				AND kk.lid = o1o.lid 
			GROUP BY o1o.mid,o1o.lid				
	 
) tm1
	LEFT JOIN o2 o2o
	ON tm1.mid = o2o.mid
		AND tm1.lid = o2o.lid
		;
			 

Exception in thread "main" java.lang.RuntimeException: side table: join condition is wrong
	at com.dtstack.flink.sql.side.SideSqlExec.getConditionFields(SideSqlExec.java:502)
	at com.dtstack.flink.sql.side.SideSqlExec.checkJoinCondition(SideSqlExec.java:455)
	at com.dtstack.flink.sql.side.SideSqlExec.joinFun(SideSqlExec.java:595)
	at com.dtstack.flink.sql.side.SideSqlExec.registerTmpTable(SideSqlExec.java:565)
	at com.dtstack.flink.sql.side.LancherMainTest.main(LancherMainTest.java:172)

加上tablename 代名 就没有报错
--create temp ooo as 
--
--	SELECT o2o.lid, tm1.mid
--	FROM (
--		SELECT o1o.lid AS lid, o1o.mid AS mid
--		FROM k kk
--			JOIN o1 o1o
--			ON kk.mid = o1o.mid
--				AND kk.lid = o1o.lid 
--			GROUP BY o1o.mid,o1o.lid				
--	 
--) tm1
--	LEFT JOIN o2 o2o
--	ON tm1.mid = o2o.mid
--		AND tm1.lid = o2o.lid
--		;

**Comment by zoudaokoulife** [comment]
这个我们修复下再推上来。

**Comment by todd5167** [comment]
master分支已经解决 @YinChunGuang
