### ISSUE TITLE
cassandra维表查询yarn per模式链接异常

### ISSUE THREAD

**Issue by chaiyuan2046** [DTStack/flinkStreamSQL#134]
1.6 分支，cassandra 作为维表查询，在local模式下可以正常执行，在yarnPer模式下会报错，报错如下：

![image](https://user-images.githubusercontent.com/16013012/60170715-9d3ca300-983b-11e9-9db0-dadfe2715b89.png)
java.lang.IllegalStateException: Can't use this cluster instance because it encountered an error in its initialization
	at com.datastax.driver.core.Cluster.checkNotClosed(Cluster.java:639)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:375)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:355)
	at com.dtstack.flink.sql.side.cassandra.CassandraAsyncReqRow.asyncInvoke(CassandraAsyncReqRow.java:222)
	at com.dtstack.flink.sql.side.cassandra.CassandraAsyncReqRow.asyncInvoke(CassandraAsyncReqRow.java:68)
	at org.apache.flink.streaming.api.operators.async.AsyncWaitOperator.processElement(AsyncWaitOperator.java:226)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:579)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:554)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:534)

**Comment by a49a** [comment]
在FlinkX 1.12中使用官方的Connector吧
