### ISSUE TITLE
No matching record in redis table leads to no output on left-join mode with RedisAsyncReqRow

### ISSUE THREAD

**Issue by cyq89051127** [DTStack/flinkStreamSQL#139]
When there's no matching records in redis table , the following code in RedisAsyncReqRow#asyncInvoke: 
    
    List<String> value = async.keys(key + ":*").get();
    String[] values = value.toArray(new String[value.size()]);
    RedisFuture<List<KeyValue<String, String>>> future =  ((RedisStringAsyncCommands) async).mget(values);
    future.thenAccept(...)
gets an exception like : 
    
    io.lettuce.core.RedisCommandExecutionException: ERR wrong number of arguments for 'mget' command
Because, when there's no matching record, the size of  returned list ('value') in first line is 0 , then returned value future of the third line will get an exception, and then the function in the  fourth line will never be executed.  At last , the resultFuture will not complete normally, there the emmiter.output method will throw an exception like following : 

    java.lang.Exception: An async function call terminated with an exception. Failing the AsyncWaitOperator.
    	at org.apache.flink.streaming.api.operators.async.Emitter.output(Emitter.java:137)
    	at org.apache.flink.streaming.api.operators.async.Emitter.run(Emitter.java:85)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Async function call has timed out.
    	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
    	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
    	at org.apache.flink.streaming.api.operators.async.queue.StreamRecordQueueEntry.get(StreamRecordQueueEntry.java:68)
    	at org.apache.flink.streaming.api.operators.async.Emitter.output(Emitter.java:129)
    	... 2 more
    Caused by: java.util.concurrent.TimeoutException: Async function call has timed out.
    	at org.apache.flink.streaming.api.functions.async.AsyncFunction.timeout(AsyncFunction.java:97)
    	at org.apache.flink.streaming.api.operators.async.AsyncWaitOperator$1.onProcessingTime(AsyncWaitOperator.java:211)
    	at org.apache.flink.streaming.runtime.tasks.SystemProcessingTimeService$TriggerTask.run(SystemProcessingTimeService.java:285)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
    	at java.util.concurrent.FutureTask.run(FutureTask.java)
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	... 1 more

I think we should handle the situation when there's no matching record in redis table.

**Comment by cyq89051127** [comment]
#140
