### ISSUE TITLE
HBase 维表报错 Async function call has timed out

### ISSUE THREAD

**Issue by lycbug666** [DTStack/flinkStreamSQL#142]
错误信息如下:
```
07/11/2019 15:23:53	Job execution switched to status FAILING.
java.lang.Exception: An async function call terminated with an exception. Failing the AsyncWaitOperator.
	at org.apache.flink.streaming.api.operators.async.Emitter.output(Emitter.java:137)
	at org.apache.flink.streaming.api.operators.async.Emitter.run(Emitter.java:85)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException: Async function call has timed out.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.apache.flink.streaming.api.operators.async.queue.StreamRecordQueueEntry.get(StreamRecordQueueEntry.java:68)
	at org.apache.flink.streaming.api.operators.async.Emitter.output(Emitter.java:129)
	... 2 more
Caused by: java.util.concurrent.TimeoutException: Async function call has timed out.
	at org.apache.flink.streaming.api.functions.async.AsyncFunction.timeout(AsyncFunction.java:97)
	at org.apache.flink.streaming.api.operators.async.AsyncWaitOperator$1.onProcessingTime(AsyncWaitOperator.java:211)
	at org.apache.flink.streaming.runtime.tasks.SystemProcessingTimeService$TriggerTask.run(SystemProcessingTimeService.java:285)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

SQL如下:

```
CREATE TABLE MyTable ( name varchar, channel varchar, pv INT) 
WITH (type = 'kafka10',bootstrapServers = 'myzk1:9092,myzk2:9092,myzk3:9092', zookeeperQuorum = 'myzk1:2181,myzk2:2181,myzk3:2181', offsetReset = 'latest',topic = 'mysql_stream',parallelism = '1');
CREATE TABLE MyResult ( channel VARCHAR, info VARCHAR)
WITH (type = 'mysql', url = 'jdbc:mysql://mysqlhost:3306/test?charset=utf8',userName = 'root',password = '123456',tableName = 'DtTestMyResult',parallelism = '1');
CREATE TABLE sideTable ( cf:channel varchar as channel, cf:info varchar as info, PRIMARY KEY (channel) , PERIOD FOR SYSTEM_TIME) 
WITH (type = 'hbase',zookeeperQuorum = 'myzk1:2181,myzk2:2181,myzk3:2181',zookeeperParent = '/hbase',tableName = 'workerinfo',cache = 'LRU', cacheSize = '10000',cacheTTLMs = '60000',parallelism = '1'); 
insert into MyResult select d.channel, d.info from ( select a.channel as channel, b.info as info from MyTable a join sideTable b on a.channel=b.channel ) as d;
```

请问这个问题如何解决?

**Comment by yangsishu** [comment]
确认下hbase的连通性没有问题

**Comment by lycbug666** [comment]
> 确认下hbase的连通性没有问题

@yangsishu 找到问题了，RowKeyEqualModeDealer#asyncGetData 方法 line76：

`Object val = HbaseUtils.convertByte(keyValue.value(), colType);`

这一行抛出了一个error，但是只catch到了exception

`java.lang.NoClassDefFoundError: org/apache/hadoop/io/RawComparator`

将 hbase-async-side/pom.xml 中exclude的 hadoop-common 重新加入可以解决

```
<excludes>
    <!--<exclude>org.apache.hadoop:hadoop-common</exclude>--
    <exclude>org.apache.hadoop:hadoop-auth</exclude>
    <exclude>org.apache.hadoop:hadoop-mapreduce-client-core</exclude>
    <exclude>org.slf4j:*</exclude>
</excludes>
```

**Comment by yangsishu** [comment]
你可以提交个pr

**Comment by todd5167** [comment]
我们环境下能执行成功的，可能你缺少hadoop-common包  @lycbug666

**Comment by polarisary** [comment]
解决了吗
