### ISSUE TITLE
多sql任务

### ISSUE THREAD

**Issue by javaBBG** [DTStack/flinkStreamSQL#148]
你好，我想咨询一下，我看githup flinksql项目你的例子，都是一个查询sql，如果对于一个source，要处理几十个sql，然后对几十个sql结果 sink到同一个表中的不同字段，这个要怎么弄？并且可能sql之间存依赖，比如b      sql依赖a sql的结果。

**Comment by liubin2048** [comment]
SQL之间的依赖你可以用create view，多个SQL落地，你可以写多个insert into啊

**Comment by hqisog** [comment]
请教下，sh submit.sh -sql D:\sideSql.txt  -name xctest -remoteSqlPluginPath /opt/dtstack/150_flinkplugin/sqlplugin   -localSqlPluginPath D:\gitspace\flinkStreamSQL\plugins   -addjar \["udf.jar\"\] -mode yarn -flinkconf D:\flink_home\kudu150etc  -yarnconf D:\hadoop\etc\hadoopkudu -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\}
 按照这个命令执行为啥会出现 
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at com.dtstack.flink.sql.launcher.LauncherOptionParser.<init>(LauncherOptionParser.java:156)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:72)
Caused by: java.lang.NullPointerException
	at org.apache.flink.hadoop.shaded.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:187)
	at com.dtstack.flink.sql.launcher.LauncherOptionParser.<init>(LauncherOptionParser.java:116)
	... 1 more

异常信息
