### ISSUE TITLE
1.7.0分支udf加载错误

### ISSUE THREAD

**Issue by tonybobam** [DTStack/flinkStreamSQL#158]
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:546)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:421)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:427)
        at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:88)
Caused by: java.lang.NoSuchMethodException: sun.misc.Launcher$AppClassLoader.addURL(java.net.URL)
        at java.lang.Class.getDeclaredMethod(Class.java:2130)
        at com.dtstack.flink.sql.util.FlinkUtil.urlClassLoaderAddUrl(FlinkUtil.java:271)
        at com.dtstack.flink.sql.util.FlinkUtil.loadExtraJar(FlinkUtil.java:262)
        at com.dtstack.flink.sql.Main.registerUDF(Main.java:259)
        at com.dtstack.flink.sql.Main.main(Main.java:168)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:529)
        ... 3 more

**Comment by zxfch** [comment]
我在1.6 release版本下yarnPer模式提交也遇到这个问题，请问有解决方法吗？

**Comment by a49a** [comment]
建议升级到1.8 和1.10
