### ISSUE TITLE
提交任务后报Could not retrieve the leader gateway.

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#17]
你好，我已经用standalone模式部署好了flink（没有用hadoop），并且start-cluster.sh启动了集群，也用nc测试了官方简单流计算任务可以执行的。但用你的项目提交作业（参数入下 sh ./submit.sh -sql /home/javajzl/testFile/flink/sqlTXT/sideSql.txt  -name xctest -remoteSqlPluginPath /opt/modules/flink-1.5.2/plugins   -localSqlPluginPath /opt/modules/flink-1.5.2/plugins   -mode standalone -flinkconf  /opt/modules/flink-1.5.2/conf -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000}
），会报找不到leader gateway错误：
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: Failed to retrieve the JobManager gateway.
	at org.apache.flink.client.program.ClusterClient.runDetached(ClusterClient.java:511)
	at org.apache.flink.client.program.StandaloneClusterClient.submitJob(StandaloneClusterClient.java:103)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:456)
	at org.apache.flink.client.program.DetachedEnvironment.finalizeExecute(DetachedEnvironment.java:77)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:402)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:68)
Caused by: org.apache.flink.util.FlinkException: Could not connect to the leading JobManager. Please check that the JobManager is running.
	at org.apache.flink.client.program.ClusterClient.getJobManagerGateway(ClusterClient.java:862)
	at org.apache.flink.client.program.ClusterClient.runDetached(ClusterClient.java:509)
	... 5 more
Caused by: org.apache.flink.runtime.leaderretrieval.LeaderRetrievalException: Could not retrieve the leader gateway.
	at org.apache.flink.runtime.util.LeaderRetrievalUtils.retrieveLeaderGateway(LeaderRetrievalUtils.java:79)
	at org.apache.flink.client.program.ClusterClient.getJobManagerGateway(ClusterClient.java:857)
	... 6 more
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at scala.concurrent.Await.result(package.scala)
	at org.apache.flink.runtime.util.LeaderRetrievalUtils.retrieveLeaderGateway(LeaderRetrievalUtils.java:77)
	... 7 more
我检查的主节点进程StandaloneSessionClusterEntrypoint 是存在的，为啥找不到gateway呢？

**Comment by yangsishu** [comment]
1.5 的standalone 模式提交是有问题在看，1.4的standalone是没问题的，1.4和1.5的yarn模式没问题

**Comment by nuaabuaa07** [comment]
flink on yarn 有2种方式。请问，这个以yarn模式提交flink计算，是需要flink 通过 yarn-session.sh启动吗？

**Comment by brightvip** [comment]
请问 1.5的这个问题 什么时候会解决呢？ 或者直接推出1.6？

**Comment by ddmonk** [comment]
1.4的standalone 经测试也出现类似问题。

**Comment by yangsishu** [comment]
yarn session，和per-job模式都可以

**Comment by yangsishu** [comment]
1.4 的standalone 模式是没问题的

**Comment by ssyue** [comment]
1.6的standalone 也有问题 同样的错 请问解决了吗 @yangsishu @zoudaokoulife

**Comment by tonychen0716** [comment]
使用https://github.com/docker-flink/docker-flink/blob/master/1.6/scala_2.11-alpine/Dockerfile，在docker环境下构建jobmananger和taskmanager，部署1.6版本的flinkStreamSQL，使用standalone模式提交任务。提示同样错误。Failed to retrieve the JobManager gateway. 内部异常信息为 Could not connect to the leading JobManager. Please check that the JobManager is running.

现在有什么解决方法或者建议吗？谢谢

**Comment by xuelvming** [comment]
我这边也发现了同样的问题，flink1.7 ，使用的也是 flinkStreamSQL的分支代码。
提示同样错误。Failed to retrieve the JobManager gateway. 内部异常信息为 Could not connect to the leading JobManager. Please check that the JobManager is running.

**Comment by lycbug666** [comment]
使用 1.5.4 版本提交 flink per-job 任务, 也提示了同样的错误

```
2019-06-18 16:32:59,441 INFO  org.apache.flink.yarn.YarnClusterClient                       - Waiting until all TaskManagers have connected
Waiting until all TaskManagers have connected
2019-06-18 16:32:59,441 INFO  org.apache.flink.yarn.YarnClusterClient                       - Starting client actor system.
2019-06-18 16:32:59,452 INFO  org.apache.flink.yarn.YarnClusterClient                       - Trying to start actor system at centose:0
2019-06-18 16:33:00,034 INFO  org.apache.flink.yarn.YarnClusterClient                       - Actor system started at akka.tcp://flink@centose:41790
2019-06-18 16:33:10,044 INFO  org.apache.flink.yarn.YarnClusterClient                       - Sending shutdown request to the Application Master
2019-06-18 16:33:10,045 INFO  org.apache.flink.yarn.YarnClusterClient                       - Start application client.
2019-06-18 16:33:10,058 INFO  org.apache.flink.yarn.ApplicationClient                       - Notification about new leader address akka.tcp://flink@cnsz22pl0527:46160/user/jobmanager with session ID 00000000-0000-0000-0000-000000000000.
2019-06-18 16:33:10,061 INFO  org.apache.flink.yarn.ApplicationClient                       - Sending StopCluster request to JobManager.
2019-06-18 16:33:10,062 INFO  org.apache.flink.yarn.ApplicationClient                       - Received address of new leader akka.tcp://flink@cnsz22pl0527:46160/user/jobmanager with session ID 00000000-0000-0000-0000-000000000000.
2019-06-18 16:33:10,062 INFO  org.apache.flink.yarn.ApplicationClient                       - Disconnect from JobManager null.
2019-06-18 16:33:10,065 INFO  org.apache.flink.yarn.ApplicationClient                       - Trying to register at JobManager akka.tcp://flink@cnsz22pl0527:46160/user/jobmanager.
2019-06-18 16:33:10,580 INFO  org.apache.flink.yarn.ApplicationClient                       - Trying to register at JobManager akka.tcp://flink@cnsz22pl0527:46160/user/jobmanager.
2019-06-18 16:33:11,081 INFO  org.apache.flink.yarn.ApplicationClient                       - Sending StopCluster request to JobManager.
2019-06-18 16:33:11,600 INFO  org.apache.flink.yarn.ApplicationClient                       - Trying to register at JobManager akka.tcp://flink@cnsz22pl0527:46160/user/jobmanager.
2019-06-18 16:33:12,100 INFO  org.apache.flink.yarn.ApplicationClient                       - Sending StopCluster request to JobManager.
2019-06-18 16:33:13,121 INFO  org.apache.flink.yarn.ApplicationClient                       - Sending StopCluster request to JobManager.
2019-06-18 16:33:13,621 INFO  org.apache.flink.yarn.ApplicationClient                       - Trying to register at JobManager akka.tcp://flink@cnsz22pl0527:46160/user/jobmanager.
2019-06-18 16:33:14,140 INFO  org.apache.flink.yarn.ApplicationClient                       - Sending StopCluster request to JobManager.
2019-06-18 16:33:15,160 INFO  org.apache.flink.yarn.ApplicationClient                       - Sending StopCluster request to JobManager.
2019-06-18 16:33:16,180 INFO  org.apache.flink.yarn.ApplicationClient                       - Sending StopCluster request to JobManager.
2019-06-18 16:33:17,190 INFO  org.apache.flink.yarn.ApplicationClient                       - Sending StopCluster request to JobManager.
2019-06-18 16:33:17,640 INFO  org.apache.flink.yarn.ApplicationClient                       - Trying to register at JobManager akka.tcp://flink@cnsz22pl0527:46160/user/jobmanager.
2019-06-18 16:33:18,200 INFO  org.apache.flink.yarn.ApplicationClient                       - Sending StopCluster request to JobManager.
2019-06-18 16:33:19,210 INFO  org.apache.flink.yarn.ApplicationClient                       - Sending StopCluster request to JobManager.
2019-06-18 16:33:20,052 WARN  org.apache.flink.yarn.YarnClusterClient                       - Error while stopping YARN cluster.
java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:157)
        at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
        at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.ready(package.scala:169)
        at scala.concurrent.Await.ready(package.scala)
        at org.apache.flink.yarn.YarnClusterClient.shutDownCluster(YarnClusterClient.java:275)
        at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:294)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:215)
        at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1035)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$9(CliFrontend.java:1111)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1754)
        at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1111)
2019-06-18 16:33:20,056 INFO  org.apache.flink.yarn.ApplicationClient                       - Stopped Application client.
2019-06-18 16:33:20,056 INFO  org.apache.flink.yarn.ApplicationClient                       - Disconnect from JobManager null.

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:545)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:420)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:404)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:798)
        at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:289)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:215)
        at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1035)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$9(CliFrontend.java:1111)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1754)
        at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1111)
Caused by: java.lang.RuntimeException: Unable to get ClusterClient status from Application Client
        at org.apache.flink.yarn.YarnClusterClient.getClusterStatus(YarnClusterClient.java:183)
        at org.apache.flink.yarn.YarnClusterClient.waitForClusterToBeReady(YarnClusterClient.java:247)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:476)
        at org.apache.flink.yarn.YarnClusterClient.submitJob(YarnClusterClient.java:157)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:464)
        at org.apache.flink.streaming.api.environment.StreamContextEnvironment.execute(StreamContextEnvironment.java:66)
        at com.dtstack.flink.sql.Main.main(Main.java:255)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:528)
        ... 12 more
Caused by: org.apache.flink.util.FlinkException: Could not connect to the leading JobManager. Please check that the JobManager is running.
        at org.apache.flink.client.program.ClusterClient.getJobManagerGateway(ClusterClient.java:932)
        at org.apache.flink.yarn.YarnClusterClient.getClusterStatus(YarnClusterClient.java:178)
        ... 23 more
Caused by: org.apache.flink.runtime.leaderretrieval.LeaderRetrievalException: Could not retrieve the leader gateway.
        at org.apache.flink.runtime.util.LeaderRetrievalUtils.retrieveLeaderGateway(LeaderRetrievalUtils.java:83)
        at org.apache.flink.client.program.ClusterClient.getJobManagerGateway(ClusterClient.java:927)
        ... 24 more
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.result(package.scala:190)
        at scala.concurrent.Await.result(package.scala)
        at org.apache.flink.runtime.util.LeaderRetrievalUtils.retrieveLeaderGateway(LeaderRetrievalUtils.java:81)
        ... 25 more
```

现在问题是否已经解决？
@yangsishu
