### ISSUE TITLE
这个flinkstreamsql使用方式

### ISSUE THREAD

**Issue by hqisog** [DTStack/flinkStreamSQL#170]
hello 能给个使用文档吗？ 关于这个 flinksqlstream 实例怎么使用？我这边用相同的启动命令，报空指针错误

**Comment by yangsishu** [comment]
在github的有文旦介绍，具体用的那个版本和报什么错信息 贴出来

**Comment by hqisog** [comment]
我这边跑 yarn模式，提交不到yarn集群上去，我看了代码，是拿不到yarn集群上的application id，所以报空指针



---原始邮件---
发件人: "whiletrue"<notifications@github.com>
发送时间: 2019年8月25日(星期日) 下午3:57
收件人: "DTStack/flinkStreamSQL"<flinkStreamSQL@noreply.github.com>;
抄送: "Leno.Han"<1286649430@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [DTStack/flinkStreamSQL] 这个flinkstreamsql使用方式 (#170)



在github的有文旦介绍，具体用的那个版本和报什么错信息 贴出来

**Comment by hqisog** [comment]
sh submit.sh -sql /data/fengkong/sql.txt  -name xctest -localSqlPluginPath /data/fengkong/jars/plugins -remoteSqlPluginPath /data/fengkong/jars/plugins -addjar \[\"udf.jar\"\]  -mode yarn -flinkconf /data/bigdata/flink-1.8.0/conf  -yarnconf /opt/cloudera/parcels/CDH/ -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\}
yarn 模式提交，为啥会报下面的问题啊？
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: No flink session found on yarn cluster.
	at com.dtstack.flink.sql.launcher.ClusterClientFactory.createYarnClient(ClusterClientFactory.java:152)
	at com.dtstack.flink.sql.launcher.ClusterClientFactory.createClusterClient(ClusterClientFactory.java:61)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:60)
Caused by: java.lang.RuntimeException: No flink session found on yarn cluster.
	at com.dtstack.flink.sql.launcher.ClusterClientFactory.createYarnClient(ClusterClientFactory.java:136)
	... 2 more

**Comment by todd5167** [comment]
@hqisog  master分支是1.5版本的flink
