### ISSUE TITLE
Kafka0.11 join mysql Null Pointer error 

### ISSUE THREAD

**Issue by hongtao12310** [DTStack/flinkStreamSQL#18]
based on flink1.4.0

the submit command
./submit.sh -sql ../mysqlsidekafka -name mysqljoinkafka -remoteSqlPluginPath /opt/flinkStreamSQL/plugins/ -localSqlPluginPath /opt/flinkStreamSQL/plugins/ -mode standalone -flinkconf /opt/flink-1.4.0/conf -confProp \{\"time.characteristic\":\"ProcessingTime\",\"sql.env.parallelism\":1\}

the log in nohup

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
---exeSql---
INSERT INTO ADJOINTRAIN
(SELECT A.AID, A.UID, B.PRODUCTID
FROM ADFEATURE AS A
INNER JOIN TRAIN AS B ON A.AID = B.AID)
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:542)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:417)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:396)
        at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:68)
Caused by: java.lang.NullPointerException
        at org.apache.commons.collections.CollectionUtils.isEqualCollection(CollectionUtils.java:305)
        at com.dtstack.flink.sql.side.SideSqlExec.checkJoinCondition(SideSqlExec.java:525)
        at com.dtstack.flink.sql.side.SideSqlExec.exec(SideSqlExec.java:131)
        at com.dtstack.flink.sql.Main.main(Main.java:186)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:525)
        ... 3 more

**Comment by hongtao12310** [comment]
我没有声明primary key  

ON已经有condition fields了 Primary key是必须的？

**Comment by zoudaokoulife** [comment]
primary key 是必须的。作为构建查询的key 和 校验 ON condition fields是否填写全
