### ISSUE TITLE
求助：standalone模式提交报错原因是什么

### ISSUE THREAD

**Issue by lucylul** [DTStack/flinkStreamSQL#183]
flink版本：1.5.0
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: Could not submit job ef3b331667b1fb720c54f626fa57b4a3.
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:247)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:464)
	at org.apache.flink.client.program.DetachedEnvironment.finalizeExecute(DetachedEnvironment.java:77)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:410)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:99)
Caused by: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
	at org.apache.flink.client.program.rest.RestClusterClient.lambda$submitJob$8(RestClusterClient.java:370)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$5(FutureUtils.java:213)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:929)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CompletionException: org.apache.flink.runtime.concurrent.FutureUtils$RetryException: Could not complete the operation. Exception is not retryable.
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
	... 12 more
Caused by: org.apache.flink.runtime.concurrent.FutureUtils$RetryException: Could not complete the operation. Exception is not retryable.
	... 10 more
Caused by: java.util.concurrent.CompletionException: org.apache.flink.runtime.rest.util.RestClientException: [Internal server error: null]
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:953)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	... 4 more
Caused by: org.apache.flink.runtime.rest.util.RestClientException: [Internal server error: null]
	at org.apache.flink.runtime.rest.RestClient.parseResponse(RestClient.java:308)
	at org.apache.flink.runtime.rest.RestClient.lambda$submitRequest$3(RestClient.java:292)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 5 more

**Comment by yangsishu** [comment]
flinkstreamsql用的是什么版本，这个要跟flink的版本对其的

**Comment by lucylul** [comment]
master节点拉的，应该版本是一致的！
还有个问题请教一下，1.8的版本yarnPer模式下，提交需要哪些依赖的jar包呢
错误信息如下：
org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot instantiate user function.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:239)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:104)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:267)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.InvalidClassException: org.apache.flink.table.runtime.aggregate.ProcessFunctionWithCleanupState; local class incompatible: stream classdesc serialVersionUID = -1829862352073642970, local class serialVersionUID = 7292478284514877734
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:616)
目前放的jar包有：
`flink-core-1.8.0.jar       flink-shaded-hadoop2-uber-3.1.0-1.8.0.jar  flink-table-api-scala_2.11-1.8.0.jar  log4j-1.2.17.jar
flink-dist_2.11-1.8.0.jar  flink-table-api-java-1.8.0.jar             flink-table-planner_2.11-1.8.0.jar    slf4j-log4j12-1.7.15.jar
`
