### ISSUE TITLE
求助：1.8 yarnper模式测试缺失jar包。

### ISSUE THREAD

**Issue by lu-uux** [DTStack/flinkStreamSQL#184]
本来报缺失flink相关的table api的jar，放入classpath后，报以下错误:
org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot load user class: com.dtstack.flink.sql.sink.rdb.format.RetractJDBCOutputFormat
ClassLoader info: URL ClassLoader:
Class not resolvable through given classloader.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:236)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:369)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:360)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:133)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:267)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.dtstack.flink.sql.sink.rdb.format.RetractJDBCOutputFormat

**Comment by lu-uux** [comment]
手动导入需要的jar到hadoop lib下可以运行，localPlugin是不是没有起作用

**Comment by maidou75293** [comment]
兄弟， 你是怎么解决的，我也遇到这个问题了  方便加个微信一起交流不  13486138676

**Comment by maidou75293** [comment]
yarn per 模式下面  源代码没有加载 插件jar

**Comment by todd5167** [comment]
@lu-uux  新发布了一版1.8_dev 可以试试
