### ISSUE TITLE
Windows系统下standalone模式下运行报错MiniCluster is not yet running.

### ISSUE THREAD

**Issue by qiuqingyu** [DTStack/flinkStreamSQL#190]
Exception in thread "main" java.lang.IllegalStateException: MiniCluster is not yet running.
	at org.apache.flink.util.Preconditions.checkState(Preconditions.java:195)
	at org.apache.flink.runtime.minicluster.MiniCluster.getHighAvailabilityServices(MiniCluster.java:223)
	at org.apache.flink.client.program.MiniClusterClient.<init>(MiniClusterClient.java:61)
	at com.dtstack.flink.sql.launcher.ClusterClientFactory.createStandaloneClient(ClusterClientFactory.java:79)
	at com.dtstack.flink.sql.launcher.ClusterClientFactory.createClusterClient(ClusterClientFactory.java:66)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:98)

**Comment by liubin2048** [comment]
这个代码默认连接的是flink的HA standalone集群，你是单master节点就会出这样的错误

**Comment by oliveryunchang** [comment]
这个问题解决了吗？

**Comment by oliveryunchang** [comment]
本地单master怎样提交基于flinkStreamSQL的任务？

**Comment by oliveryunchang** [comment]
这个HA standalone集群怎么搭建的？我这边使用K8S已经搭建了两个JobManager，但是还是提示"MiniCluster is not yet running"
