### ISSUE TITLE
1.8 版本  yarn 模式 提交不成功，什么问题

### ISSUE THREAD

**Issue by maidou75293** [DTStack/flinkStreamSQL#196]

**Comment by qiuqingyu** [comment]
你那里什么报错啊？我这里也是一直不成功

**Comment by todd5167** [comment]
@maidou75293 @qiuqingyu   新推了一版本1.8_dev可以在试试，需要拷贝flink-table-common-1.8.1.jar和flink-table-planner_2.11-1.8.1.jar到flinklib下。

**Comment by qiuqingyu** [comment]
> @maidou75293 @qiuqingyu 新推了一版本1.8_dev可以在试试，需要拷贝flink-table-common-1.8.1.jar和flink-table-planner_2.11-1.8.1.jar到flinklib下。

好的，非常感谢，我试下

**Comment by taiziwang** [comment]
拷贝flink-table-common-1.8.1.jar和flink-table-planner_2.11-1.8.1.jar到flinklib下，
以1.8 版本 yarnPer 模式还是提交不上去：
 报错如下:
  yarn-container报错:org/apache/flink/yarn/entrypoint/yarnJobclusterEntrypoint:Unsuppered major.minor version 52.0

shell提交 客户端报错:
    exception in thread "main" org.apache.flink.client.deployment.clusterdeployexception:cloud not deploy yarn job cluster;
  at org.apache.flink.yarn.yarnclusterdescriptor.deployjobclusger(YarnClusterDescriptor.java:82)
  at com.dtstack.flink.sql.launcher.perjob.PerJobSumitter.submit(PerJobSubmitter.java:78)
  at com.dtstack.flink.sql.laucher.laucherMain.main(LaucherMain.java:97)
  caused by:org.apache.flink.yarn.AbstractYarnClusterDescriptor$YarnDeploymentException:the yarn application unexpectedly switched to state failed during deloyment.

**Comment by todd5167** [comment]
@taiziwang  你的Jdk版本不是1.8吧

**Comment by taiziwang** [comment]
@todd5167 #  是的 大数据环境是jdk1.7搭建的 但是submit提交参数项-finkconf目录下的文件flink-conf.yaml指定参数env.java.home和containerized.master/taskmanager.env均指向jdk1.8的目录   但还是报上述类版本不兼容问题？感觉flink-conf没有生效
