### ISSUE TITLE
1.7.0yarn和standalone提交都报错，请帮忙看下原因，谢谢

### ISSUE THREAD

**Issue by xuxiaoxiao89** [DTStack/flinkStreamSQL#197]
提交命令：java -cp /opt/cep/lib/sql.launcher-1.0-SNAPSHOT.jar com.dtstack.flink.sql.launcher.LauncherMain -mode yarn -sql /opt/cep/sql/console2.sql -name test -localSqlPluginPath /opt/hadoopclient/flinkclient/Flink/flink/lib/ -remoteSqlPluginPath /opt/cep/plugins/ -confProp {\"time.characteristic\":\"EventTime\"} -flinkconf /opt/cep/flinkconf/ -yarnconf /opt/cep/yarnconf/

报错：Exception in thread "main" java.lang.RuntimeException: org.apache.flink.client.deployment.ClusterRetrieveException: Couldn't retrieve Yarn cluster
	at com.dtstack.flink.sql.launcher.ClusterClientFactory.createYarnClient(ClusterClientFactory.java:123)
	at com.dtstack.flink.sql.launcher.ClusterClientFactory.createClusterClient(ClusterClientFactory.java:54)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:87)
Caused by: org.apache.flink.client.deployment.ClusterRetrieveException: Couldn't retrieve Yarn cluster
	at org.apache.flink.yarn.AbstractYarnClusterDescriptor.retrieve(AbstractYarnClusterDescriptor.java:409)
	at com.dtstack.flink.sql.launcher.ClusterClientFactory.createYarnClient(ClusterClientFactory.java:119)
	... 2 more
Caused by: java.io.IOException: Could not create FileSystem for highly available storage (high-availability.storageDir)
	at org.apache.flink.runtime.blob.BlobUtils.createFileSystemBlobStore(BlobUtils.java:119)
	at org.apache.flink.runtime.blob.BlobUtils.createBlobStoreFromConfig(BlobUtils.java:92)
	at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.createHighAvailabilityServices(HighAvailabilityServicesUtils.java:121)
	at org.apache.flink.client.program.ClusterClient.<init>(ClusterClient.java:159)
	at org.apache.flink.client.program.rest.RestClusterClient.<init>(RestClusterClient.java:185)
	at org.apache.flink.client.program.rest.RestClusterClient.<init>(RestClusterClient.java:158)
	at org.apache.flink.yarn.YarnClusterDescriptor.createYarnClusterClient(YarnClusterDescriptor.java:96)
	at org.apache.flink.yarn.AbstractYarnClusterDescriptor.retrieve(AbstractYarnClusterDescriptor.java:401)
	... 3 more
Caused by: java.io.IOException: Cannot instantiate file system for URI: hdfs://hacluster/flink/recovery
	at org.apache.flink.runtime.fs.hdfs.HadoopFsFactory.create(HadoopFsFactory.java:187)
	at org.apache.flink.core.fs.FileSystem.getUnguardedFileSystem(FileSystem.java:399)
	at org.apache.flink.core.fs.FileSystem.get(FileSystem.java:318)
	at org.apache.flink.core.fs.Path.getFileSystem(Path.java:298)
	at org.apache.flink.runtime.blob.BlobUtils.createFileSystemBlobStore(BlobUtils.java:116)
	... 10 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.hdfs.server.namenode.ha.AdaptiveFailoverProxyProvider not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:1927)
	at org.apache.hadoop.hdfs.NameNodeProxies.getFailoverProxyProviderClass(NameNodeProxies.java:409)
	at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:139)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:579)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:524)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:146)
	at org.apache.flink.runtime.fs.hdfs.HadoopFsFactory.create(HadoopFsFactory.java:159)
	... 14 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.hdfs.server.namenode.ha.AdaptiveFailoverProxyProvider not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:1895)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:1919)
	... 20 more
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.hdfs.server.namenode.ha.AdaptiveFailoverProxyProvider not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:1801)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:1893)
	... 21 more

**Comment by todd5167** [comment]
flink1.7分支以及standalone提交模式我们内部不维护了，你可以使用flink1.8_dev分支，以yarnPer模式执行。

**Comment by todd5167** [comment]
@xuxiaoxiao89
