### ISSUE TITLE
flink join 维表出现on条件找不到的问题 已经设置primary key

### ISSUE THREAD

**Issue by 383747787** [DTStack/flinkStreamSQL#204]
![image](https://user-images.githubusercontent.com/3955416/66793377-b6bf4300-ef2f-11e9-9d59-5b175b4af93a.png)

T表是流表，A表和B表是维表
pk都设置了

Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:546)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:421)
	at org.apache.flink.client.program.OptimizerPlanEnvironment.getOptimizedPlan(OptimizerPlanEnvironment.java:83)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:78)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:120)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:117)
Caused by: java.lang.RuntimeException: ON condition must contain all equal fields!!!
	at com.dtstack.flink.sql.side.SideSqlExec.joinFun(SideSqlExec.java:583)
	at com.dtstack.flink.sql.side.SideSqlExec.registerTmpTable(SideSqlExec.java:552)
	at com.dtstack.flink.sql.Main.main(Main.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:529)
	... 5 more

**Comment by todd5167** [comment]
@383747787   你主键绑定了两个属性，join中的连接条件就得使用这两个属性，否则就是这个错误。
你把主键的第二个字段都去掉，就可以了

**Comment by 383747787** [comment]
> @383747787 你主键绑定了两个属性，join中的连接条件就得使用这两个属性，否则就是这个错误。
> 你把主键的第二个字段都去掉，就可以了

我爸tableB的room_id去掉了 还是报了一样的错误 我们用的是flink 1.6版本 不知道是不是版本问题？

**Comment by todd5167** [comment]
@383747787  第一个表主键的point_location_id 去掉了吗

**Comment by 383747787** [comment]
> @383747787 第一个表主键的point_location_id 去掉了吗

嗯嗯 可以了 我明白这个pk的真正含义了  是被join表的 on字段 左边虽然也用到 但是不是右表 所以也要去掉 感谢
