### ISSUE TITLE
1.8版本时间窗口遇到的问题

### ISSUE THREAD

**Issue by lucylul** [DTStack/flinkStreamSQL#210]
yarnPer模式，任务提交正常，运行失败报错：
19/11/06 10:44:34 INFO executiongraph.ExecutionGraph: groupBy: (name), window: (TumblingGroupWindow('w$, 'PROCTIME, 60000.millis)), select: (name, COUNT(*) AS endtime, COUNT(sgrade) AS grade) -> select: (1 AS id, name, 2019-11-06 02:44:23 AS createtime, endtime, grade) -> to: Tuple2 -> Sink: student (1/1) (d7ecd041522d91b1807be2891ca0baaa) switched from RUNNING to FAILED.
java.lang.IllegalStateException: no serializer and no type info
	at org.apache.flink.util.Preconditions.checkState(Preconditions.java:195)
	at org.apache.flink.api.common.state.StateDescriptor.initializeSerializerUnlessSet(StateDescriptor.java:285)
	at org.apache.flink.runtime.state.AbstractKeyedStateBackend.getOrCreateKeyedState(AbstractKeyedStateBackend.java:284)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.getOrCreateKeyedState(AbstractStreamOperator.java:568)
	at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.open(WindowOperator.java:240)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:424)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:290)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:745)
19/11/06 10:44:34 INFO executiongraph.ExecutionGraph: Job test (6c5201cc487aa6b610b76387e96df954) switched from state RUNNING to FAILING.

**Comment by yangsishu** [comment]
把sql贴下

**Comment by lucylul** [comment]
sql脚本：
CREATE TABLE flinkkafka(
id varchar,
name varchar,
stime datetime,
sgrade int, WATERMARK FOR stime AS withOffset( stime , 3000 ) )WITH(
    type ='kafka09',
    bootstrapServers ='192.168.9.86:6667',
    zookeeperQuorum ='192.168.9.86:2181',
    offsetReset ='latest',
    topic ='oo',
    groupId ='e3ca31c6ff7511e9bba6801844ec1810_55B88C8B36C0E80C938B1D4F95C1CA01',
    parallelism ='1'
 );
CREATE TABLE student(
id varchar,
name varchar,
createtime timestamp,
endtime datetime,
grade int )WITH(
    type ='mysql',
    url ='jdbc:mysql://192.168.20.128:3306/test',
    userName ='root',
    password ='root',
    tableName ='student',
    parallelism ='1'
 );
INSERT INTO student
SELECT
'1' id,
name,
CURRENT_TIMESTAMP() createtime,
TUMBLE_END(ROWTIME, INTERVAL '1' MINUTE) endtime,
cast(count(sgrade) AS int) grade
FROM flinkkafka
GROUP BY TUMBLE(ROWTIME, INTERVAL '1' MINUTE), name

**Comment by todd5167** [comment]
@lucylul   flinklib目录下有flink-table-api-java-1.8.1.jar包吗？没有需要手动加进去

**Comment by lucylul** [comment]
@todd5167 jar包有放，是1.8.0版本的有关系吗

**Comment by lucylul** [comment]
@todd5167 
file: '/home/hive/flinkStreamSQL/plugins/kafka09source/kafka09-source-1.8.0_release.jar' (missing)
file: '/home/hive/flinkStreamSQL/plugins/mysqlsink/mysql-sink-1.8.0_release.jar' (missing)
换成稳定版报这个问题，插件已经放到指定位置了，是哪里不对吗？

**Comment by todd5167** [comment]
@lucylul 提交的节点插件名称和工作节点的插件名称一致吧，都是xxx-1.8.0_release.jar。 如果classpath模式不方便也可以用shipfile模式，不需要每台节点都放插件包

**Comment by lucylul** [comment]
通过shipfile模式，可以解决此问题
