### ISSUE TITLE
yarn 模式下提交不成功

### ISSUE THREAD

**Issue by panzhenyu12** [DTStack/flinkStreamSQL#219]
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: Could not submit job ()
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:250)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:483)
	at org.apache.flink.client.program.DetachedEnvironment.finalizeExecute(DetachedEnvironment.java:77)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:429)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:100)
Caused by: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
	at org.apache.flink.client.program.rest.RestClusterClient.lambda$submitJob$8(RestClusterClient.java:388)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$5(FutureUtils.java:208)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.apache.flink.runtime.concurrent.FutureUtils$Timeout.run(FutureUtils.java:943)
	at org.apache.flink.runtime.concurrent.DirectExecutorService.execute(DirectExecutorService.java:211)
	at org.apache.flink.runtime.concurrent.FutureUtils.lambda$orTimeout$11(FutureUtils.java:361)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException

**Comment by panzhenyu12** [comment]
这个是大概是什么原因呢，该怎么去排查问题？

**Comment by panzhenyu12** [comment]
查了下日志
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:129)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
19/11/19 11:39:07 INFO executiongraph.ExecutionGraph: Job sqltest (de05549403433a4189811c5dd815d6c2) switched from state RUNNING to FAILING.

**Comment by zhihui-ge** [comment]
有可能和使用的flink版本及flinkStreamSQL的分支有关

**Comment by todd5167** [comment]
@panzhenyu12 jackson那个包我们使用的外部的，没打进去。新推了一版，core包包含了相关依赖类，你可以再试试。

**Comment by panzhenyu12** [comment]
多谢~~
