### ISSUE TITLE
HBase Sink Table如何定义？

### ISSUE THREAD

**Issue by zhihui-ge** [DTStack/flinkStreamSQL#222]
SQL语句
CREATE TABLE dh_account_info(
	f1:product_id VARCHAR,
	f1:account_id VARCHAR,
	f1:dev_imei VARCHAR,
	f1:dev_uuid VARCHAR,
	f1:from_ch VARCHAR,
	f1:ad_channel VARCHAR,
	f1:ad_subchannel VARCHAR,
	f1:dev_os VARCHAR,
	f1:dev_model VARCHAR,
	f1:dev_brand VARCHAR,
	f1:third_account_id VARCHAR,
	f1:account_type VARCHAR,
	f1:first_login_time VARCHAR,
	f1:first_login_ip VARCHAR
)WITH(
	type ='hbase',
	zookeeperQuorum ='192.168.112.40:12181,192.168.112.41:12181,192.168.112.46:12181',
	tableName ='dh:dh_account_info',
	rowKey ='f1:account_id,f1:product_id',
	parallelism ='1',
	zookeeperParent ='/hbase-unsecure'
);

INSERT
INTO
    dh_account_info
SELECT
	product_id,
	account_id,
	dev_imei,
	dev_uuid,
	from_ch,
	ad_channel,
	ad_subchannel,
	dev_os,
	dev_model,
	dev_brand,
	third_account_id,
	account_type,
	record_time AS first_login_time,
	ip AS first_login_ip
FROM
	dh_ods_ods_dh_account_login;

Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Field name of query result and registered TableSink dh_account_info do not match.
Query result schema: product_id,account_id,dev_imei,dev_uuid,from_ch,ad_channel,ad_subchannel,dev_os,dev_model,dev_brand,third_account_id,account_type,first_login_time,first_login_ip
TableSink schema: f1:product_id,f1:account_id,f1:dev_imei,f1:dev_uuid,f1:from_ch,f1:ad_channel,f1:ad_subchannel,f1:dev_os,f1:dev_model,f1:dev_brand,f1:third_account_id,f1:account_type,f1:first_login_time,f1:first_login_ip
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:546)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:421)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:423)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:100)
Caused by: org.apache.flink.table.api.ValidationException: Field name of query result and registered TableSink dh_account_info do not match.
Query result schema: product_id,account_id,dev_imei,dev_uuid,from_ch,ad_channel,ad_subchannel,dev_os,dev_model,dev_brand,third_account_id,account_type,first_login_time,first_login_ip
TableSink schema: f1:product_id,f1:account_id,f1:dev_imei,f1:dev_uuid,f1:from_ch,f1:ad_channel,f1:ad_subchannel,f1:dev_os,f1:dev_model,f1:dev_brand,f1:third_account_id,f1:account_type,f1:first_login_time,f1:first_login_ip
	at com.dtstack.flink.sql.exec.FlinkSQLExec.sqlUpdate(FlinkSQLExec.java:79)
	at com.dtstack.flink.sql.Main.sqlTranslation(Main.java:197)
	at com.dtstack.flink.sql.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:529)
	... 3 more

**Comment by oliveryunchang** [comment]
怎么解决这个异常的？

**Comment by zhihui-ge** [comment]
1.8的分支提交pr，这个问题应该解决了
