### ISSUE TITLE
1.6版本本地提交报错Could not read taskmanager.memory.size

### ISSUE THREAD

**Issue by yangBin666** [DTStack/flinkStreamSQL#23]
本地环境：linux，flinkStreamSql-1.6分支
启动脚本
` java -cp /data/flink/test/lib/*  com.dtstack.flink.sql.launcher.LauncherMain -sql /data/flink/test/test.txt  -name xctest     -localSqlPluginPath /data/flink/test/plugins    -mode local   -confProp {\"sql.checkpoint.interval\":10000}
`
报错：
`Exception in thread "main" org.apache.flink.configuration.IllegalConfigurationException: Could not read taskmanager.memory.size
	at org.apache.flink.runtime.taskexecutor.TaskManagerServicesConfiguration.fromConfiguration(TaskManagerServicesConfiguration.java:236)
	at org.apache.flink.runtime.minicluster.LocalFlinkMiniCluster.startTaskManager(LocalFlinkMiniCluster.scala:234)
	at org.apache.flink.runtime.minicluster.FlinkMiniCluster$$anonfun$3.apply(FlinkMiniCluster.scala:389)
	at org.apache.flink.runtime.minicluster.FlinkMiniCluster$$anonfun$3.apply(FlinkMiniCluster.scala:382)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.flink.runtime.minicluster.FlinkMiniCluster.start(FlinkMiniCluster.scala:382)
	at org.apache.flink.runtime.minicluster.FlinkMiniCluster.start(FlinkMiniCluster.scala:324)
	at com.dtstack.flink.sql.MyLocalStreamEnvironment.execute(MyLocalStreamEnvironment.java:115)
	at com.dtstack.flink.sql.Main.main(Main.java:203)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:60)
Caused by: java.lang.NumberFormatException: text does not start with a number
	at org.apache.flink.configuration.MemorySize.parseBytes(MemorySize.java:178)
	at org.apache.flink.configuration.MemorySize.parse(MemorySize.java:131)
	at org.apache.flink.configuration.MemorySize.parse(MemorySize.java:148)
	at org.apache.flink.runtime.taskexecutor.TaskManagerServicesConfiguration.fromConfiguration(TaskManagerServicesConfiguration.java:233)
`

**Comment by yangBin666** [comment]
>

**Comment by mjbrandy** [comment]
请问，您这个问题是怎么解决的，我也报这个错，感谢
