### ISSUE TITLE
维表多连接条件开启keyby有个BUG

### ISSUE THREAD

**Issue by lucylul** [DTStack/flinkStreamSQL#246]
维表多连接条件场景，加入了partitionedJoin='true'时，报错信息：Caused by: org.apache.flink.api.common.InvalidProgramException: This type (GenericType<org.apache.flink.types.Row>) cannot be used as key.
	at org.apache.flink.api.common.operators.Keys$ExpressionKeys.<init>(Keys.java:330)
	at org.apache.flink.streaming.api.datastream.DataStream.keyBy(DataStream.java:337)
	at com.dtstack.flink.sql.side.SideSqlExec.joinFun(SideSqlExec.java:751)
	at com.dtstack.flink.sql.side.SideSqlExec.exec(SideSqlExec.java:136)
	at com.dtstack.flink.sql.Main.sqlTranslation(Main.java:187)
	at com.dtstack.flink.sql.Main.main(Main.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:529)
	... 5 more

**Comment by yangsishu** [comment]
最好把sql贴下

**Comment by lucylul** [comment]
维表相关的部分：
CREATE TABLE users(
buildingNum VARCHAR,
communityName VARCHAR,
roomNum VARCHAR,
streetName VARCHAR,
villageName VARCHAR,
cellNum VARCHAR,
PRIMARY KEY(communityName,roomNum,villageName,cellNum),
PERIOD FOR SYSTEM_TIME
  )WITH(
     type='mysql',
     url='jdbc:mysql://192.168.0.128/test',
     userName='root',
     password='root',
     tableName='user_base',
     cache ='LRU',
     cacheSize ='10000',
     cacheTTLMs ='60000',
     parallelism ='1',
     partitionedJoin='true'
  );
insert into test_qt
	SELECT
		t1.id ID,
		t1.villageName zjmc,
		t1.streetName sqmc,
		t1.communityName xqmc,
		t1.bulidingNum zh,
		t1.cellNum dyh,
		t1.roomNum hh,
		'4' sjzl,
		'ss' sjzlxq,
		to_tm(t1.cc) sbsj,
		t1.dataOrigin sjly,
		to_tm(t1.weighTime) czsj
		from test_sx t1
		join users t2
		on t1.villageName = t2.villageName
		and t1.roomNum = t2.roomNum
		and t1.cellNum = t2.cellNum
		and t1.communityName = t2.communityName;

**Comment by todd5167** [comment]
@lucylul   内部已经修复了，最近会推出来

**Comment by oliveryunchang** [comment]
@todd5167 相关修复提交了吗？如果提交了能否给出commit id链接
