### ISSUE TITLE
纯kafka消息输出到oracle报错 重复的列名

### ISSUE THREAD

**Issue by zjfplayer** [DTStack/flinkStreamSQL#250]
我们的环境是kafka0.10，oracle19c，然后使用了1.8release分支上的代码，参照com.dtstack.flink.sql.side.SideSqlExecTest测试类的写法，使用了如下sql脚本进行测试：
<pre>`
-- 纯kafka消息输出
CREATE TABLE kafkaTable(
    pk varchar,
    curr_time bigint,
    msg_index bigint,
    send_time varchar,
    WATERMARK FOR curr_time AS withOffset(curr_time,1000)
 )WITH(
    type='kafka10',
    bootstrapServers='tdh-1:9092,tdh-2:9092,tdh-3:9092',
    offsetReset='latest',
    topic='testSimpleOutput'
 );
CREATE TABLE flink_simpleoutput(
    PK varchar,
    CURR_TIME bigint,
    MSG_INDEX bigint,
    SEND_TIME varchar,
    INSERT_TIME timestamp
 )WITH(
    type='oracle',
    url='jdbc:oracle:thin:@192.168.73.229:1521/ORCLCDB',
    userName='zjf',
    password='zjf',
    tableName='FLINK_SIMPLEOUTPUT',
--     schema = 'zjf',
--     parallelism ='1'
 );
insert
into
    flink_simpleoutput
    select
        pk as PK,
        curr_time as CURR_TIME,
        msg_index as MSG_INDEX,
        send_time as SEND_TIME,
        CURRENT_TIMESTAMP as INSERT_TIME
    from
        kafkaTable;`
</pre>
其中的oracle建表语句为：
<pre>`
CREATE TABLE flink_simpleoutput(
    pk varchar(50) primary key,
    curr_time NUMBER(20),
    msg_index NUMBER(20),
    send_time varchar(50),
    insert_time timestamp
);
`</pre>
kafka的消息格式为：
`{"send_time":"2020-01-09 09:51:19","msg_index":2,"curr_time":1578534679200,"pk":"e15b6dcf-ceae-44a1-aaba-c8faee8872eb"}`，
运行时报错信息如下：
<pre>
`java.sql.SQLSyntaxErrorException: ORA-00957: 重复的列名

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:270)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:91)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:970)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1426)
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:3756)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3736)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1063)
	at com.dtstack.flink.sql.sink.rdb.format.RetractJDBCOutputFormat.writeSingleRecord(RetractJDBCOutputFormat.java:209)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.dtstack.flink.sql.sink.rdb.format.RetractJDBCOutputFormat.submitExecuteBatch(RetractJDBCOutputFormat.java:321)
	at com.dtstack.flink.sql.sink.rdb.format.RetractJDBCOutputFormat.insertWrite(RetractJDBCOutputFormat.java:197)
	at com.dtstack.flink.sql.sink.rdb.format.RetractJDBCOutputFormat.writeRecord(RetractJDBCOutputFormat.java:180)
	at com.dtstack.flink.sql.sink.rdb.format.RetractJDBCOutputFormat.writeRecord(RetractJDBCOutputFormat.java:52)
	at org.apache.flink.streaming.api.functions.sink.OutputFormatSinkFunction.invoke(OutputFormatSinkFunction.java:86)
	at org.apache.flink.streaming.api.functions.sink.SinkFunction.invoke(SinkFunction.java:52)
	at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:56)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:579)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:554)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:534)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:718)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:696)
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:41)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:579)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:554)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:534)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:718)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:696)
	at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:51)
	at org.apache.flink.table.runtime.CRowWrappingCollector.collect(CRowWrappingCollector.scala:37)
	at org.apache.flink.table.runtime.CRowWrappingCollector.collect(CRowWrappingCollector.scala:28)
	at DataStreamCalcRule$33.processElement(Unknown Source)
	at org.apache.flink.table.runtime.CRowProcessRunner.processElement(CRowProcessRunner.scala:66)
	at org.apache.flink.table.runtime.CRowProcessRunner.processElement(CRowProcessRunner.scala:35)
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:579)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:554)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:534)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:718)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:696)
	at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:51)
	at org.apache.flink.table.runtime.CRowWrappingCollector.collect(CRowWrappingCollector.scala:37)
	at org.apache.flink.table.runtime.CRowWrappingCollector.collect(CRowWrappingCollector.scala:28)
	at DataStreamSourceConversion$22.processElement(Unknown Source)
	at org.apache.flink.table.runtime.CRowOutputProcessRunner.processElement(CRowOutputProcessRunner.scala:70)
	at org.apache.flink.streaming.api.operators.ProcessOperator.processElement(ProcessOperator.java:66)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:579)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:554)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:534)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:718)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:696)
	at org.apache.flink.streaming.runtime.operators.TimestampsAndPeriodicWatermarksOperator.processElement(TimestampsAndPeriodicWatermarksOperator.java:67)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:579)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:554)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:534)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:718)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:696)
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:41)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:579)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:554)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:534)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:718)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:696)
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:41)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:579)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:554)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:534)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:718)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:696)
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:41)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:579)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:554)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:534)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:718)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:696)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollectWithTimestamp(StreamSourceContexts.java:310)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collectWithTimestamp(StreamSourceContexts.java:409)
	at org.apache.flink.streaming.connectors.kafka.internals.AbstractFetcher.emitRecordWithTimestamp(AbstractFetcher.java:398)
	at org.apache.flink.streaming.connectors.kafka.internal.Kafka010Fetcher.emitRecord(Kafka010Fetcher.java:91)
	at org.apache.flink.streaming.connectors.kafka.internal.Kafka09Fetcher.runFetchLoop(Kafka09Fetcher.java:156)
	at org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumerBase.run(FlinkKafkaConsumerBase.java:712)
	at com.dtstack.flink.sql.source.kafka.CustomerKafka010Consumer.run(CustomerKafka010Consumer.java:64)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:93)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:57)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:97)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Error : 957, Position : 348, Sql = MERGE INTO "FLINK_SIMPLEOUTPUT" T1 USING (SELECT :1  "PK",:2  "CURR_TIME",:3  "MSG_INDEX",:4  "SEND_TIME",:5  "INSERT_TIME" FROM DUAL) T2 ON (T1."PK"=T2."PK" OR T1."PK"=T2."PK")  WHEN MATCHED THEN UPDATE SET "T1"."CURR_TIME"="T2"."CURR_TIME","T1"."MSG_INDEX"="T2"."MSG_INDEX","T1"."SEND_TIME"="T2"."SEND_TIME","T1"."INSERT_TIME"="T2"."INSERT_TIME","T1"."CURR_TIME"="T2"."CURR_TIME","T1"."MSG_INDEX"="T2"."MSG_INDEX","T1"."SEND_TIME"="T2"."SEND_TIME","T1"."INSERT_TIME"="T2"."INSERT_TIME" WHEN NOT MATCHED THEN INSERT ("PK","CURR_TIME","MSG_INDEX","SEND_TIME","INSERT_TIME") VALUES ("T2"."PK","T2"."CURR_TIME","T2"."MSG_INDEX","T2"."SEND_TIME","T2"."INSERT_TIME"), OriginalSql = MERGE INTO "FLINK_SIMPLEOUTPUT" T1 USING (SELECT ? "PK",? "CURR_TIME",? "MSG_INDEX",? "SEND_TIME",? "INSERT_TIME" FROM DUAL) T2 ON (T1."PK"=T2."PK" OR T1."PK"=T2."PK")  WHEN MATCHED THEN UPDATE SET "T1"."CURR_TIME"="T2"."CURR_TIME","T1"."MSG_INDEX"="T2"."MSG_INDEX","T1"."SEND_TIME"="T2"."SEND_TIME","T1"."INSERT_TIME"="T2"."INSERT_TIME","T1"."CURR_TIME"="T2"."CURR_TIME","T1"."MSG_INDEX"="T2"."MSG_INDEX","T1"."SEND_TIME"="T2"."SEND_TIME","T1"."INSERT_TIME"="T2"."INSERT_TIME" WHEN NOT MATCHED THEN INSERT ("PK","CURR_TIME","MSG_INDEX","SEND_TIME","INSERT_TIME") VALUES ("T2"."PK","T2"."CURR_TIME","T2"."MSG_INDEX","T2"."SEND_TIME","T2"."INSERT_TIME"), Error Msg = ORA-00957: 重复的列名

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
	... 94 more`
</pre>
我看了下报错信息里面的sql，发现不知道为什么有些字段被加了2次，请问下这个是我的sql执行脚本有问题，还是项目本身的bug？
<pre>
`MERGE INTO "FLINK_SIMPLEOUTPUT" T1 
USING (SELECT :1  "PK",:2  "CURR_TIME",:3  "MSG_INDEX",:4  "SEND_TIME",:5  "INSERT_TIME" FROM DUAL) T2 
ON (T1."PK"=T2."PK" OR T1."PK"=T2."PK")  
WHEN MATCHED 
	THEN 
		UPDATE SET "T1"."CURR_TIME"="T2"."CURR_TIME",
		"T1"."MSG_INDEX"="T2"."MSG_INDEX",
		"T1"."SEND_TIME"="T2"."SEND_TIME",
		"T1"."INSERT_TIME"="T2"."INSERT_TIME",
		"T1"."CURR_TIME"="T2"."CURR_TIME",
		"T1"."MSG_INDEX"="T2"."MSG_INDEX",
		"T1"."SEND_TIME"="T2"."SEND_TIME",
		"T1"."INSERT_TIME"="T2"."INSERT_TIME" 
WHEN NOT MATCHED 
	THEN 
		INSERT ("PK","CURR_TIME","MSG_INDEX","SEND_TIME","INSERT_TIME") 
		VALUES ("T2"."PK","T2"."CURR_TIME","T2"."MSG_INDEX","T2"."SEND_TIME","T2"."INSERT_TIME"), 
OriginalSql = ;
MERGE INTO "FLINK_SIMPLEOUTPUT" T1 
	USING (SELECT ? "PK",? "CURR_TIME",? "MSG_INDEX",? "SEND_TIME",? "INSERT_TIME" FROM DUAL) T2 
	ON (T1."PK"=T2."PK" OR T1."PK"=T2."PK")  
WHEN MATCHED 
	THEN 
		UPDATE SET "T1"."CURR_TIME"="T2"."CURR_TIME",
		"T1"."MSG_INDEX"="T2"."MSG_INDEX",
		"T1"."SEND_TIME"="T2"."SEND_TIME",
		"T1"."INSERT_TIME"="T2"."INSERT_TIME",
		"T1"."CURR_TIME"="T2"."CURR_TIME",
		"T1"."MSG_INDEX"="T2"."MSG_INDEX",
		"T1"."SEND_TIME"="T2"."SEND_TIME",
		"T1"."INSERT_TIME"="T2"."INSERT_TIME" 
WHEN NOT MATCHED 
	THEN 
		INSERT ("PK","CURR_TIME","MSG_INDEX","SEND_TIME","INSERT_TIME") 
		VALUES ("T2"."PK","T2"."CURR_TIME","T2"."MSG_INDEX","T2"."SEND_TIME","T2"."INSERT_TIME"); 
`
</pre>

**Comment by todd5167** [comment]
@zjfplayer    这个内部修复了，字段放入集合的时候没做存在检查。

**Comment by zjfplayer** [comment]
> @zjfplayer 这个内部修复了，字段放入集合的时候没做存在检查。

开源版本后续还更新吗？我看已经很久没有发布新的release版本了

**Comment by zjfplayer** [comment]
开源版本后续还更新吗？我看已经很久没有发布新的release版本了
@todd5167

**Comment by todd5167** [comment]
@zjfplayer   年前更新一版的。

**Comment by yangsishu** [comment]
后面会一个月推一次的；这个开源项目我们会持续维护的
