### ISSUE TITLE
使用mode为yarn模式时报classnotfound

### ISSUE THREAD

**Issue by zjfplayer** [DTStack/flinkStreamSQL#252]
这是我的启动命令：
`sh /opt/flinkStreamSQL/bin/submit.sh -sql /opt/flinkStreamSQL/bin/flinkTest/1.sql  -name xctest -remoteSqlPluginPath /opt/flinkStreamSQL/plugins/ -localSqlPluginPath /opt/flinkStreamSQL/plugins/  -mode yarn -flinkconf /opt/flink/conf  -yarnconf /etc/hadoop/conf.cloudera.yarn/ -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\} -yarnSessionConf \{\"yid\":\"application_1579173051549_0001\"}`
起来后发现yarn日志里面报错了：
<pre>
`020-01-16 19:19:03,147 INFO  org.apache.flink.runtime.jobmaster.JobMaster                  - JobManager successfully registered at ResourceManager, leader id: a8709f72aad5348e16b8cfcd17c14637.
2020-01-16 19:19:03,147 INFO  org.apache.flink.runtime.jobmaster.slotpool.SlotPoolImpl      - Requesting new slot [SlotRequestId{28d166700e3270e83ccda66867d4b264}] and profile ResourceProfile{cpuCores=-1.0, heapMemoryInMB=-1, directMemoryInMB=0, nativeMemoryInMB=0, networkMemoryInMB=0} from resource manager.
2020-01-16 19:19:03,148 INFO  org.apache.flink.yarn.YarnResourceManager                     - Request slot with profile ResourceProfile{cpuCores=-1.0, heapMemoryInMB=-1, directMemoryInMB=0, nativeMemoryInMB=0, networkMemoryInMB=0} for job 653908840964d60d671650fb769cfdf2 with allocation id 0c280f5ff8946d06c51f6c8c3654c62c.
2020-01-16 19:19:03,152 INFO  org.apache.flink.yarn.YarnResourceManager                     - Requesting new TaskExecutor container with resources <memory:4096, vCores:1>. Number pending requests 1.
2020-01-16 19:19:04,853 INFO  org.apache.flink.runtime.checkpoint.CheckpointCoordinator     - Checkpoint triggering task Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 -> Sink: flink_simpleoutput (1/1) of job 653908840964d60d671650fb769cfdf2 is not in state RUNNING but SCHEDULED instead. Aborting checkpoint.
2020-01-16 19:19:07,535 INFO  org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl         - Received new token for : uf30-1:8041
2020-01-16 19:19:07,545 INFO  org.apache.flink.yarn.YarnResourceManager                     - Received new container: container_e02_1579173051549_0001_01_000002 - Remaining pending container requests: 1
2020-01-16 19:19:07,546 INFO  org.apache.flink.yarn.YarnResourceManager                     - Removing container request Capability[<memory:4096, vCores:1>]Priority[1]. Pending container requests 0.
2020-01-16 19:19:07,630 INFO  org.apache.flink.yarn.YarnResourceManager                     - Creating container launch context for TaskManagers
2020-01-16 19:19:07,631 INFO  org.apache.flink.yarn.YarnResourceManager                     - Starting TaskManagers
2020-01-16 19:19:07,639 INFO  org.apache.hadoop.yarn.client.api.impl.ContainerManagementProtocolProxy  - Opening proxy : uf30-1:8041
2020-01-16 19:19:13,740 INFO  org.apache.flink.yarn.YarnResourceManager                     - Registering TaskManager with ResourceID container_e02_1579173051549_0001_01_000002 (akka.tcp://flink@uf30-1:46897/user/taskmanager_0) at ResourceManager
2020-01-16 19:19:13,855 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 -> Sink: flink_simpleoutput (1/1) (4e7b1a961bd9a0fedeaad5f5b84bed47) switched from SCHEDULED to DEPLOYING.
2020-01-16 19:19:13,855 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Deploying Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 -> Sink: flink_simpleoutput (1/1) (attempt #0) to container_e02_1579173051549_0001_01_000002 @ uf30-1 (dataPort=58937)
2020-01-16 19:19:14,213 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 -> Sink: flink_simpleoutput (1/1) (4e7b1a961bd9a0fedeaad5f5b84bed47) switched from DEPLOYING to RUNNING.
2020-01-16 19:19:14,629 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 -> Sink: flink_simpleoutput (1/1) (4e7b1a961bd9a0fedeaad5f5b84bed47) switched from RUNNING to FAILED.
java.lang.NoClassDefFoundError: org/apache/flink/table/sinks/RetractStreamTableSink
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:126)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)
	at java.io.ObjectStreamClass.getDeclaredSUID(ObjectStreamClass.java:1857)
	at java.io.ObjectStreamClass.access$700(ObjectStreamClass.java:79)
	at java.io.ObjectStreamClass$3.run(ObjectStreamClass.java:506)
	at java.io.ObjectStreamClass$3.run(ObjectStreamClass.java:494)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:494)
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:391)
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:681)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1939)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1805)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2096)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2341)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2265)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2123)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2341)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2265)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2123)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:566)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:552)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:540)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:501)
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:224)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:369)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:360)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:360)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:360)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:360)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:360)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:360)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:133)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:267)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.table.sinks.RetractStreamTableSink
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:120)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 59 more`
</pre>

然后我部署是flink1.8.1 on yarn，flinkStreamSQL打包后上传到了服务器上：
<pre>
`[root@uf30-1 bin]# ll /opt/flinkStreamSQL/
total 4
drwxr-xr-x.  3 root root   54 Jan 16 19:19 bin
drwxr-xr-x.  2 root root   42 Jan 16 17:28 lib
drwxr-xr-x. 43 root root 4096 Jan 16 17:28 plugins`
</pre>

**Comment by zjfplayer** [comment]
yarnPer模式解决了，使用了
<pre>
`sh /opt/flinkStreamSQL/bin/submit.sh -sql /opt/flinkStreamSQL/bin/flinkTest/1.sql  -name xctest -remoteSqlPluginPath /opt/flinkStreamSQL/plugins/ -localSqlPluginPath /opt/flinkStreamSQL/plugins/  -mode yarnPer -flinkconf /opt/flink/conf -flinkJarPath /opt/flink/lib  -pluginLoadMode shipfile -yarnconf /etc/hadoop/conf.cloudera.yarn/ -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\}`
</pre>
需要将打包出来的lib目录下的jar文件放到flink的lib下
