### ISSUE TITLE
1.8.1版本启动报错

### ISSUE THREAD

**Issue by zjfplayer** [DTStack/flinkStreamSQL#255]
1.8.0运行正常，1.8.1无法运行
启动命令：
<pre>
sh /opt/flinkStreamSQL/bin/submit.sh -sql /opt/flinkStreamSQL/bin/flinkTest/1.sql  -name xctest -remoteSqlPluginPath /opt/flinkStreamSQL/plugins/ -localSqlPluginPath /opt/flinkStreamSQL/plugins/  -mode yarnPer -flinkconf /opt/flink/conf -flinkJarPath /opt/flink/lib  -pluginLoadMode shipfile -yarnconf /etc/hadoop/conf.cloudera.yarn/ -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\}
</pre>

sql信息：
<pre>
CREATE TABLE kafkaTable(
    pk varchar,
    curr_time bigint,
    msg_index bigint,
    send_time varchar
--     ,
--     WATERMARK FOR curr_time AS withOffset(curr_time,1000)
 )WITH(
    type='kafka10',
    bootstrapServers='uf30-1:9092,uf30-2:9092,uf30-3:9092',
    offsetReset='latest',
    topic='testSimpleOutput'
 );
CREATE TABLE flink_simpleoutput(
    pk varchar,
    curr_time bigint,
    msg_index bigint,
    send_time varchar
--     ,
--     insert_time timestamp
 )WITH(
    type='mysql',
    url='jdbc:mysql://192.168.71.70:3306/hs_dap?charset=utf8',
    userName='hs_dap',
    password='hundsun',
    tableName='flink_simpleoutput',
    parallelism ='2'
 );
insert
into
    flink_simpleoutput
    select
        pk,
        curr_time,
        msg_index,
        send_time
--         ,
--         current_timestamp as insert_time
    from
        kafkaTable a;
</pre>

报错信息：
<pre>
20/01/21 10:04:51 INFO checkpoint.CheckpointCoordinator: Checkpoint triggering task Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Filter -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 (1/1) of job 4fad4511277d48e45a751347cf144a2c is not in state RUNNING but SCHEDULED instead. Aborting checkpoint.
20/01/21 10:04:54 INFO yarn.YarnResourceManager: Registering TaskManager with ResourceID container_e02_1579173051549_0007_01_000003 (akka.tcp://flink@uf30-2:11859/user/taskmanager_0) at ResourceManager
20/01/21 10:04:54 INFO executiongraph.ExecutionGraph: Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Filter -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 (1/1) (a1c0c60a7462163f4b7bfa715f000bee) switched from SCHEDULED to DEPLOYING.
20/01/21 10:04:54 INFO executiongraph.ExecutionGraph: Deploying Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Filter -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 (1/1) (attempt #0) to container_e02_1579173051549_0007_01_000002 @ uf30-1 (dataPort=40868)
20/01/21 10:04:54 INFO executiongraph.ExecutionGraph: Sink: flink_simpleoutput (1/2) (80578cadc00ab8f2326bceb4bfe36d77) switched from SCHEDULED to DEPLOYING.
20/01/21 10:04:54 INFO executiongraph.ExecutionGraph: Deploying Sink: flink_simpleoutput (1/2) (attempt #0) to container_e02_1579173051549_0007_01_000003 @ uf30-2 (dataPort=55016)
20/01/21 10:04:54 INFO executiongraph.ExecutionGraph: Sink: flink_simpleoutput (2/2) (74c423f0d0503ede1cf0227b213d997d) switched from SCHEDULED to DEPLOYING.
20/01/21 10:04:54 INFO executiongraph.ExecutionGraph: Deploying Sink: flink_simpleoutput (2/2) (attempt #0) to container_e02_1579173051549_0007_01_000002 @ uf30-1 (dataPort=40868)
20/01/21 10:04:54 INFO executiongraph.ExecutionGraph: Sink: flink_simpleoutput (1/2) (80578cadc00ab8f2326bceb4bfe36d77) switched from DEPLOYING to RUNNING.
20/01/21 10:04:54 INFO executiongraph.ExecutionGraph: Sink: flink_simpleoutput (2/2) (74c423f0d0503ede1cf0227b213d997d) switched from DEPLOYING to RUNNING.
20/01/21 10:04:54 INFO executiongraph.ExecutionGraph: Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Filter -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 (1/1) (a1c0c60a7462163f4b7bfa715f000bee) switched from DEPLOYING to RUNNING.
20/01/21 10:04:55 INFO executiongraph.ExecutionGraph: Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Filter -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 (1/1) (a1c0c60a7462163f4b7bfa715f000bee) switched from RUNNING to FAILED.
org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot instantiate user function.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:239)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:369)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:360)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:360)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:133)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:267)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: unexpected exception type
	at java.io.ObjectStreamClass.throwMiscException(ObjectStreamClass.java:1736)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1266)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2132)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2341)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2265)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2123)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:566)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:552)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:540)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:501)
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:224)
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1260)
	... 23 more
Caused by: java.lang.IllegalArgumentException: Invalid lambda deserialization
	at com.dtstack.flink.sql.Main.$deserializeLambda$(Main.java:96)
	... 33 more
20/01/21 10:04:55 INFO executiongraph.ExecutionGraph: Job xctest (4fad4511277d48e45a751347cf144a2c) switched from state RUNNING to FAILING.
org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot instantiate user function.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:239)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:369)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:360)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:360)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:296)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:133)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:267)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: unexpected exception type
	at java.io.ObjectStreamClass.throwMiscException(ObjectStreamClass.java:1736)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1266)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2132)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2341)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2265)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2123)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1624)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:566)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:552)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:540)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:501)
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:224)
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1260)
	... 23 more
Caused by: java.lang.IllegalArgumentException: Invalid lambda deserialization
	at com.dtstack.flink.sql.Main.$deserializeLambda$(Main.java:96)
	... 33 more
</pre>

**Comment by zjfplayer** [comment]
这是1.8.0版本运行正常的日志：
<pre>
20/01/21 10:33:37 INFO yarn.YarnResourceManager: Received new container: container_e02_1579173051549_0008_01_000003 - Remaining pending container requests: 1
20/01/21 10:33:37 INFO yarn.YarnResourceManager: Removing container request Capability[<memory:1024, vCores:1>]Priority[1]. Pending container requests 0.
20/01/21 10:33:37 INFO yarn.YarnResourceManager: Creating container launch context for TaskManagers
20/01/21 10:33:37 INFO yarn.YarnResourceManager: Starting TaskManagers
20/01/21 10:33:37 INFO impl.ContainerManagementProtocolProxy: Opening proxy : uf30-2:8041
20/01/21 10:33:38 INFO checkpoint.CheckpointCoordinator: Checkpoint triggering task Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 (1/1) of job c3170070c060630da71c7dac293312fe is not in state RUNNING but SCHEDULED instead. Aborting checkpoint.
20/01/21 10:33:40 INFO yarn.YarnResourceManager: Registering TaskManager with ResourceID container_e02_1579173051549_0008_01_000003 (akka.tcp://flink@uf30-2:58231/user/taskmanager_0) at ResourceManager
20/01/21 10:33:40 INFO executiongraph.ExecutionGraph: Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 (1/1) (25fd1546e1f30d5c4fbaff38e7f290cd) switched from SCHEDULED to DEPLOYING.
20/01/21 10:33:40 INFO executiongraph.ExecutionGraph: Deploying Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 (1/1) (attempt #0) to container_e02_1579173051549_0008_01_000002 @ uf30-2 (dataPort=16074)
20/01/21 10:33:40 INFO executiongraph.ExecutionGraph: Sink: flink_simpleoutput (1/2) (b131ddf29701439f046f0c931376f0d6) switched from SCHEDULED to DEPLOYING.
20/01/21 10:33:40 INFO executiongraph.ExecutionGraph: Deploying Sink: flink_simpleoutput (1/2) (attempt #0) to container_e02_1579173051549_0008_01_000003 @ uf30-2 (dataPort=15248)
20/01/21 10:33:40 INFO executiongraph.ExecutionGraph: Sink: flink_simpleoutput (2/2) (d044447680a07d294eeff8fa3140c793) switched from SCHEDULED to DEPLOYING.
20/01/21 10:33:40 INFO executiongraph.ExecutionGraph: Deploying Sink: flink_simpleoutput (2/2) (attempt #0) to container_e02_1579173051549_0008_01_000002 @ uf30-2 (dataPort=16074)
20/01/21 10:33:40 INFO executiongraph.ExecutionGraph: Sink: flink_simpleoutput (2/2) (d044447680a07d294eeff8fa3140c793) switched from DEPLOYING to RUNNING.
20/01/21 10:33:40 INFO executiongraph.ExecutionGraph: Sink: flink_simpleoutput (1/2) (b131ddf29701439f046f0c931376f0d6) switched from DEPLOYING to RUNNING.
20/01/21 10:33:40 INFO executiongraph.ExecutionGraph: Source: testSimpleOutput_kafkaTable -> Map -> to: Tuple2 -> Map -> from: (pk, curr_time, msg_index, send_time, PROCTIME) -> select: (pk, curr_time, msg_index, send_time) -> to: Tuple2 (1/1) (25fd1546e1f30d5c4fbaff38e7f290cd) switched from DEPLOYING to RUNNING.
20/01/21 10:33:48 INFO checkpoint.CheckpointCoordinator: Triggering checkpoint 1 @ 1579574028650 for job c3170070c060630da71c7dac293312fe.
20/01/21 10:33:48 INFO checkpoint.CheckpointCoordinator: Completed checkpoint 1 for job c3170070c060630da71c7dac293312fe (1242 bytes in 298 ms).
20/01/21 10:33:58 INFO checkpoint.CheckpointCoordinator: Triggering checkpoint 2 @ 1579574038650 for job c3170070c060630da71c7dac293312fe.
20/01/21 10:33:58 INFO checkpoint.CheckpointCoordinator: Completed checkpoint 2 for job c3170070c060630da71c7dac293312fe (1242 bytes in 24 ms).
20/01/21 10:34:08 INFO checkpoint.CheckpointCoordinator: Triggering checkpoint 3 @ 1579574048650 for job c3170070c060630da71c7dac293312fe.
20/01/21 10:34:08 INFO checkpoint.CheckpointCoordinator: Completed checkpoint 3 for job c3170070c060630da71c7dac293312fe (1242 bytes in 35 ms).
20/01/21 10:34:18 INFO checkpoint.CheckpointCoordinator: Triggering checkpoint 4 @ 1579574058649 for job c3170070c060630da71c7dac293312fe.
20/01/21 10:34:18 INFO checkpoint.CheckpointCoordinator: Completed checkpoint 4 for job c3170070c060630da71c7dac293312fe (1242 bytes in 33 ms).
20/01/21 10:34:28 INFO checkpoint.CheckpointCoordinator: Triggering checkpoint 5 @ 1579574068650 for job c3170070c060630da71c7dac293312fe.
20/01/21 10:34:28 INFO checkpoint.CheckpointCoordinator: Completed checkpoint 5 for job c3170070c060630da71c7dac293312fe (1242 bytes in 26 ms).
</pre>
