### ISSUE TITLE
1.8.0版本中关于join side table的问题

### ISSUE THREAD

**Issue by zjfplayer** [DTStack/flinkStreamSQL#256]
请问下，关于消息表关联维度表，若维度表数据量很大，想用索引，但是发现1.8.0版本中对于sql校验时，sideTable只能直接用join，不能通过先where过滤再join，例如：
<pre>
insert into 
...
from
    kafkaTable a
left join
   (select * from 
    mysqlSideTable b
   where  b.a_year=2018 and b.a_month=9) bb
on a.a_v1=bb.a_v1 
</pre>
会报错：
<pre>
side-table must be used in join operator
java.lang.RuntimeException: side-table must be used in join operator
	at com.dtstack.flink.sql.side.SideSQLParser.parseSql(SideSQLParser.java:112)
	at com.dtstack.flink.sql.side.SideSQLParser.parseSql(SideSQLParser.java:132)
	at com.dtstack.flink.sql.side.SideSQLParser.parseRightNode(SideSQLParser.java:261)
	at com.dtstack.flink.sql.side.SideSQLParser.dealJoinNode(SideSQLParser.java:214)
	at com.dtstack.flink.sql.side.SideSQLParser.parseSql(SideSQLParser.java:123)
	at com.dtstack.flink.sql.side.SideSQLParser.parseSql(SideSQLParser.java:106)
	at com.dtstack.flink.sql.side.SideSQLParser.parseSql(SideSQLParser.java:102)
	at com.dtstack.flink.sql.side.SideSQLParser.getExeQueue(SideSQLParser.java:81)
	at com.dtstack.flink.sql.side.SideSqlExec.exec(SideSqlExec.java:100)
	at com.dtstack.flink.sql.Main.sqlTranslation(Main.java:189)
	at com.dtstack.flink.sql.Main.main(Main.java:150)
</pre>
也不能在on条件里面加上sideTable的过滤条件,例如：
<pre>
insert into 
...
from
    kafkaTable a
left join
    mysqlSideTable b
on a.a_v1=b.a_v1 and b.a_year=2018 and b.a_month=9;
</pre>
会报错：
<pre>
java.lang.ClassCastException: org.apache.calcite.sql.SqlNumericLiteral cannot be cast to org.apache.calcite.sql.SqlIdentifier
	at com.dtstack.flink.sql.side.SideSqlExec.getConditionFields(SideSqlExec.java:641)
	at com.dtstack.flink.sql.side.SideSqlExec.checkJoinCondition(SideSqlExec.java:616)
	at com.dtstack.flink.sql.side.SideSqlExec.joinFun(SideSqlExec.java:752)
	at com.dtstack.flink.sql.side.SideSqlExec.exec(SideSqlExec.java:143)
	at com.dtstack.flink.sql.Main.sqlTranslation(Main.java:189)
	at com.dtstack.flink.sql.Main.main(Main.java:150)
	at com.hundsun.flink.sql.side.PerformanceTest.test(PerformanceTest.java:166)
	at com.hundsun.flink.sql.side.PerformanceTest.testLeftJoin(PerformanceTest.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
</pre>
如果在on后再加上where条件过滤的话，其实索引也是失效了把：
<pre>
insert into 
...
from
    kafkaTable a
left join
    mysqlSideTable b
on a.a_v1=b.a_v1 
where b.a_year=2018 and b.a_month=9;
</pre>

那当我维度表数据量很大又不能使用索引的时候，如何加速查询呢？这会是一个性能瓶颈把？

**Comment by todd5167** [comment]
@zjfplayer   后续版本会有维表的谓词下推，where b.a_year=2018 and b.a_month=9; 查询维表的时候会填充该谓词信息
