### ISSUE TITLE
提交至配置了HA的standalone模式flink报未描述HDFS路径错误

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#26]
提交命令为：
sh ./submit.sh -sql /home/jinzhiliang/test/flink/sqlTXT/sideSql.txt  -name xctest -remoteSqlPluginPath /home/dl/projects/flink-1.4.2/plugins   -localSqlPluginPath /home/dl/projects/flink-1.4.2/plugins   -mode standalone  -flinkconf  /home/dl/projects/flink-1.4.2/conf -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000}

集群已standalone模式部署，并配置了HA。单独flink提交作业时正常，但是使用finkstreamSQL提交作业时报错：
Exception in thread "main" java.lang.RuntimeException: Couldn't retrieve standalone cluster
	at org.apache.flink.client.deployment.StandaloneClusterDescriptor.retrieve(StandaloneClusterDescriptor.java:49)
	at com.dtstack.flink.sql.launcher.ClusterClientFactory.createStandaloneClient(ClusterClientFactory.java:70)
	at com.dtstack.flink.sql.launcher.ClusterClientFactory.createClusterClient(ClusterClientFactory.java:59)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:60)
Caused by: java.io.IOException: Could not create FileSystem for highly available storage (high-availability.storageDir)
	at org.apache.flink.runtime.blob.BlobUtils.createFileSystemBlobStore(BlobUtils.java:119)
	at org.apache.flink.runtime.blob.BlobUtils.createBlobStoreFromConfig(BlobUtils.java:92)
	at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.createHighAvailabilityServices(HighAvailabilityServicesUtils.java:103)
	at org.apache.flink.client.program.ClusterClient.<init>(ClusterClient.java:144)
	at org.apache.flink.client.program.StandaloneClusterClient.<init>(StandaloneClusterClient.java:44)
	at org.apache.flink.client.deployment.StandaloneClusterDescriptor.retrieve(StandaloneClusterDescriptor.java:47)
	... 3 more
Caused by: java.io.IOException: The given file system URI (hdfs:///flink/ha) did not describe the authority (like for example HDFS NameNode address/port or S3 host). The attempt to use a configured default authority failed: Hadoop configuration for default file system ('fs.default.name' or 'fs.defaultFS') contains no valid authority component (like hdfs namenode, S3 host, etc)
	at org.apache.flink.runtime.fs.hdfs.HadoopFsFactory.create(HadoopFsFactory.java:149)
	at org.apache.flink.core.fs.FileSystem.getUnguardedFileSystem(FileSystem.java:401)
	at org.apache.flink.core.fs.FileSystem.get(FileSystem.java:320)
	at org.apache.flink.core.fs.Path.getFileSystem(Path.java:293)
	at org.apache.flink.runtime.blob.BlobUtils.createFileSystemBlobStore(BlobUtils.java:116)

请问，是否支持standalone模式的HA集群。

**Comment by jjj450554498** [comment]
hdfs的路径缺少ip:port，建议检查一下hdfs的配置文件

**Comment by nuaabuaa07** [comment]
我配置的是HA standalone模式的flink，使用flinkStreamSQL提交任务时不需要配置hadoop相关配置文件的路径吧？如果需要，是在yarnconf这个参数指定吗？

**Comment by zoudaokoulife** [comment]
配置ha standalone 模式会用到hdfs相关设置。在yarnconf指定即可
