### ISSUE TITLE
维表关联partitionedJoin配置导致异常问题，修复了吗？

### ISSUE THREAD

**Issue by oliveryunchang** [DTStack/flinkStreamSQL#260]
```
CREATE TABLE side_mongo_rdw_dim_dy_room (
    id BIGINT,
    show_status BIGINT
    ,PRIMARY KEY(id)
    ,PERIOD FOR SYSTEM_TIME
)WITH(
    type ='mongo'
    ,address ='*******'
    ,userName ='****'
    ,password ='****'
    ,database ='**'
    ,tableName ='flink_test'
    ,parallelism ='1'
    ,cache ='LRU'
    ,cacheSize ='10000'
    ,cacheTTLMs ='60000'
    ,partitionedJoin='true'
);
```
提示异常：
```
Exception in thread "main" org.apache.flink.api.common.InvalidProgramException: This type (GenericType<org.apache.flink.types.Row>) cannot be used as key.
	at org.apache.flink.api.common.operators.Keys$ExpressionKeys.<init>(Keys.java:330)
	at org.apache.flink.streaming.api.datastream.DataStream.keyBy(DataStream.java:337)
```
查看发现已经有人提过类似的issue：https://github.com/DTStack/flinkStreamSQL/issues/246
，但是在commits里面没找到对应的提交

**Comment by todd5167** [comment]
@oliveryunchang   修复了，commit e2c5643736591b877bc4c5f31c4ec08bbe0b4084。下一个版本会有一些变更。
