### ISSUE TITLE
是否支持多流式源表的union all 操作？

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#27]
测试输出代码： 
insert
 into
	TargTable02
	
	select c.height , c.name from
	(
		(
		select 
			a.height,
			a.name
		from
			StreamSrcTable a
		where a.name = 'Tom'
		)
		union all 
		(
		select 
			b.height,
			b.name
		from
			StreamSrcTable02 b
		where b.name ='Jery'
		)
	) c
	;

经过测试，当被union的2个表为同一个表时，输出正常。当union的2个表为2个不同的源表时，会报错：
	at org.apache.flink.table.calcite.FlinkPlannerImpl.validate(FlinkPlannerImpl.scala:89)
	... 11 more
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Object 'STREAMSRCTABLE' not found
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by yangsishu** [comment]
flink是支持union all 的语法，我这边测试下

**Comment by nuaabuaa07** [comment]
是支持多流式源表的union all 操作吗？我在用flinkStreamSQL提交任务时，会报其中一个源表找不到。

**Comment by yanxi0227** [comment]
@nuaabuaa07 1.5.0版本已经支持union all语法
