### ISSUE TITLE
请教下一个问题：yarnper模式，container中TaskManager报flink-conf.yaml不存在

### ISSUE THREAD

**Issue by mosence** [DTStack/flinkStreamSQL#273]
环境如下：
centos7
CDH-5.16.1-1.cdh5.16.1
flink 1.8.3
flinksql 1.8-release 最新提交 a83e54419991e0b2f120ccac600f16d94d9ca9d5
执行提交后jobmanager正常
taskmanager执行报错，请问下这种情况大概问题出现在哪？

taskmanager.log

```
2020-03-09 14:53:55,117 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -  Starting YARN TaskExecutor runner (Version: 1.8.3, Rev:d54807b, Date:05.12.2019 @ 14:16:18 CST)
2020-03-09 14:53:55,117 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -  OS current user: yarn
2020-03-09 14:53:55,519 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -  Current Hadoop/Kerberos user: yarn
2020-03-09 14:53:55,519 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -  JVM: Java HotSpot(TM) 64-Bit Server VM - Oracle Corporation - 1.8/25.202-b08
2020-03-09 14:53:55,519 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -  Maximum heap size: 345 MiBytes
2020-03-09 14:53:55,519 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -  JAVA_HOME: /usr/java/jdk1.8.0_202
2020-03-09 14:53:55,520 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -  Hadoop version: 2.6.5
2020-03-09 14:53:55,520 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -  JVM Options:
2020-03-09 14:53:55,520 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -     -Xms360m
2020-03-09 14:53:55,520 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -     -Xmx360m
2020-03-09 14:53:55,520 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -     -XX:MaxDirectMemorySize=664m
2020-03-09 14:53:55,520 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -     -Dlog.file=/data/yarn/container-logs/application_1583489391845_0052/container_1583489391845_0052_01_000003/taskmanager.log
2020-03-09 14:53:55,520 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -     -Dlogback.configurationFile=file:./logback.xml
2020-03-09 14:53:55,520 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -     -Dlog4j.configuration=file:./log4j.properties
2020-03-09 14:53:55,521 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -  Program Arguments:
2020-03-09 14:53:55,521 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -     --configDir
2020-03-09 14:53:55,521 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -     .
2020-03-09 14:53:55,521 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -     -Dweb.port=0
2020-03-09 14:53:55,521 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -     -Djobmanager.rpc.address=cdh3
2020-03-09 14:53:55,521 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -     -Dweb.tmpdir=/tmp/flink-web-4d9e2154-76fe-48ef-b59d-b237a28d0337
2020-03-09 14:53:55,521 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -     -Djobmanager.rpc.port=40859
2020-03-09 14:53:55,521 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -     -Drest.address=cdh3
2020-03-09 14:53:55,521 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  -  Classpath: 
[CDH-5.16.1-1.cdh5.16.1 Hadoop Classpath]
2020-03-09 14:53:55,522 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  - --------------------------------------------------------------------------------
2020-03-09 14:53:55,523 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  - Registered UNIX signal handlers for [TERM, HUP, INT]
2020-03-09 14:53:55,525 INFO  org.apache.flink.yarn.YarnTaskExecutorRunner                  - Current working Directory: /data/yarn/nm/usercache/yarn/appcache/application_1583489391845_0052/container_1583489391845_0052_01_000003
2020-03-09 14:53:55,534 ERROR org.apache.flink.yarn.YarnTaskExecutorRunner                  - YARN TaskManager initialization failed.
org.apache.flink.configuration.IllegalConfigurationException: The Flink config file '/data/yarn/nm/usercache/yarn/appcache/application_1583489391845_0052/container_1583489391845_0052_01_000003/flink-conf.yaml' (/data/yarn/nm/usercache/yarn/appcache/application_1583489391845_0052/container_1583489391845_0052_01_000003) does not exist.
	at org.apache.flink.configuration.GlobalConfiguration.loadConfiguration(GlobalConfiguration.java:112)
	at org.apache.flink.yarn.YarnTaskExecutorRunner.run(YarnTaskExecutorRunner.java:114)
	at org.apache.flink.yarn.YarnTaskExecutorRunner.main(YarnTaskExecutorRunner.java:82)
```

**Comment by mosence** [comment]
已经发现问题，我重新编译不同hadoop版本少包原因。
