### ISSUE TITLE
在1.10版本中发现的窗口机制存在的问题

### ISSUE THREAD

**Issue by zhouxinhai** [DTStack/flinkStreamSQL#303]
我将袋鼠云从1.8升级到1.10, 原先在1.8引擎下可以正常运行的sql语句会报错。
sql语句如下：

```
CREATE TABLE MyTable(
    name varchar,
    channel varchar,
    pv INT,
    xctime bigint,
    CHARACTER_LENGTH(channel) AS timeLeng,
	WATERMARK FOR xctime AS withOffset( xctime,0)
 )WITH(
    type ='kafka10',
    bootstrapServers ='hw-bd-01:9092',
    zookeeperQuorum ='hw-bd-01:2181/kafka',
    offsetReset ='earliest',
    topic ='zxh_test',
    parallelism ='1',
    topicIsPattern='false'
 );

CREATE TABLE MyResult(
    name VARCHAR,
    cnt BIGINT
 )WITH(
    type ='console',
    parallelism ='1'
 );


insert
into
    MyResult
    select
        d.name,
        count(d.channel) as cnt
    from
        MyTable as d group by d.name,TUMBLE(d.xctime, INTERVAL '1' SECOND) having count(d.channel) > 1
```

启动参数为：

`-confProp {\"time.characteristic\":\"EventTime\"}`

这个用例在1.8上是可以正常运行的，但是在1.10下会报错：
```
Exception in thread "main" org.apache.flink.table.api.ValidationException: SQL validation failed. From line 4, column 22 to line 4, column 62: Cannot apply 'TUMBLE' to arguments of type 'TUMBLE(<BIGINT>, <INTERVAL SECOND>)'. Supported form(s): 'TUMBLE(<DATETIME>, <DATETIME_INTERVAL>)'
'TUMBLE(<DATETIME>, <DATETIME_INTERVAL>, <TIME>)'
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$validate(FlinkPlannerImpl.scala:130)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.validate(FlinkPlannerImpl.scala:105)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:127)
	at com.dtstack.flink.sql.exec.FlinkSQLExec.extractQueryTableFromInsertCaluse(FlinkSQLExec.java:111)
	at com.dtstack.flink.sql.exec.FlinkSQLExec.sqlUpdate(FlinkSQLExec.java:63)
	at com.dtstack.flink.sql.exec.ExecuteProcessHelper.sqlTranslation(ExecuteProcessHelper.java:230)
	at com.dtstack.flink.sql.exec.ExecuteProcessHelper.getStreamExecution(ExecuteProcessHelper.java:168)
	at com.dtstack.flink.sql.Main.main(Main.java:42)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:138)
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 4, column 22 to line 4, column 62: Cannot apply 'TUMBLE' to arguments of type 'TUMBLE(<BIGINT>, <INTERVAL SECOND>)'. Supported form(s): 'TUMBLE(<DATETIME>, <DATETIME_INTERVAL>)'
'TUMBLE(<DATETIME>, <DATETIME_INTERVAL>, <TIME>)'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:834)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:819)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4840)
	at org.apache.calcite.sql.SqlCallBinding.newValidationSignatureError(SqlCallBinding.java:280)
	at org.apache.calcite.sql.type.FamilyOperandTypeChecker.checkSingleOperandType(FamilyOperandTypeChecker.java:96)
	at org.apache.calcite.sql.type.FamilyOperandTypeChecker.checkOperandTypes(FamilyOperandTypeChecker.java:130)
	at org.apache.calcite.sql.type.CompositeOperandTypeChecker.checkOperandTypes(CompositeOperandTypeChecker.java:255)
	at org.apache.calcite.sql.SqlOperator.checkOperandTypes(SqlOperator.java:668)
	at org.apache.calcite.sql.SqlOperator.validateOperands(SqlOperator.java:432)
	at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:303)
	at org.apache.calcite.sql.SqlFunction.deriveType(SqlFunction.java:219)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5599)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$DeriveTypeVisitor.visit(SqlValidatorImpl.java:5586)
	at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:139)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveTypeImpl(SqlValidatorImpl.java:1690)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.deriveType(SqlValidatorImpl.java:1675)
	at org.apache.calcite.sql.SqlNode.validateExpr(SqlNode.java:236)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateGroupClause(SqlValidatorImpl.java:3971)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3379)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1007)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:967)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:216)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:942)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:649)
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.org$apache$flink$table$planner$calcite$FlinkPlannerImpl$$validate(FlinkPlannerImpl.scala:126)
	... 8 more
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Cannot apply 'TUMBLE' to arguments of type 'TUMBLE(<BIGINT>, <INTERVAL SECOND>)'. Supported form(s): 'TUMBLE(<DATETIME>, <DATETIME_INTERVAL>)'
'TUMBLE(<DATETIME>, <DATETIME_INTERVAL>, <TIME>)'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:572)
	... 35 more
```
我试着将水印时间改为timestamp类型

```
CREATE TABLE MyTable(
    name varchar,
    channel varchar,
    pv INT,
    xctime timestamp,
    CHARACTER_LENGTH(channel) AS timeLeng,
	WATERMARK FOR xctime AS withOffset( xctime,0)
 )WITH(
    type ='kafka10',
    bootstrapServers ='hw-bd-01:9092',
    zookeeperQuorum ='hw-bd-01:2181/kafka',
    offsetReset ='earliest',
    topic ='zxh_test',
    parallelism ='1',
    topicIsPattern='false'
 );
```
但是报错的内容是：
```
Exception in thread "main" java.lang.IllegalArgumentException: not support type of LocalDateTime, current only support(timestamp, long).
	at com.dtstack.flink.sql.watermarker.WaterMarkerAssigner.assignWaterMarker(WaterMarkerAssigner.java:78)
	at com.dtstack.flink.sql.exec.ExecuteProcessHelper.registerTable(ExecuteProcessHelper.java:294)
	at com.dtstack.flink.sql.exec.ExecuteProcessHelper.getStreamExecution(ExecuteProcessHelper.java:163)
	at com.dtstack.flink.sql.Main.main(Main.java:42)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:138)
```

**Comment by todd5167** [comment]
@zhouxinhai    时间戳类型的问题，我们尽快修复下，非常感谢！

**Comment by zhouxinhai** [comment]
这个问题我后续又做了一下跟踪。在1.10中修改insert语句后是可以执行的：
```
insert
into
    MyResult
    select
        d.name,
        count(d.channel) as cnt
    from
        MyTable as d group by d.name,TUMBLE(d.ROWTIME, INTERVAL '1' SECOND) having count(d.channel) > 1
```
说明：我将TUMBLE中的d.xctime改为了d.ROWTIME。（ROWTIME必须大写）

但是修改后的语句在1.8下面执行就会报错，报错内容如下：
```
10:42:11.920 [ERROR] [o.a.calcite.runtime.CalciteException    :59  ] [main                    ] - org.apache.calcite.sql.validate.SqlValidatorException: Column 'ROWTIME' not found in table 'd'
10:42:11.922 [ERROR] [o.a.calcite.runtime.CalciteException    :61  ] [main                    ] - org.apache.calcite.runtime.CalciteContextException: From line 4, column 33 to line 4, column 41: Column 'ROWTIME' not found in table 'd'
Exception in thread "main" org.apache.flink.table.api.ValidationException: SQL validation failed. From line 4, column 33 to line 4, column 41: Column 'ROWTIME' not found in table 'd'
	at org.apache.flink.table.calcite.FlinkPlannerImpl.validate(FlinkPlannerImpl.scala:109)
	at com.dtstack.flink.sql.exec.FlinkSQLExec.sqlUpdate(FlinkSQLExec.java:60)
	at com.dtstack.flink.sql.exec.ExecuteProcessHelper.sqlTranslation(ExecuteProcessHelper.java:233)
	at com.dtstack.flink.sql.exec.ExecuteProcessHelper.getStreamExecution(ExecuteProcessHelper.java:170)
	at com.dtstack.flink.sql.Main.main(Main.java:43)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:91)
Caused by: org.apache.calcite.runtime.CalciteContextException: From line 4, column 33 to line 4, column 41: Column 'ROWTIME' not found in table 'd'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:783)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:768)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:4764)
	at org.apache.calcite.sql.validate.DelegatingScope.fullyQualify(DelegatingScope.java:439)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visit(SqlValidatorImpl.java:5624)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$ExtendedExpander.visit(SqlValidatorImpl.java:5817)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$ExtendedExpander.visit(SqlValidatorImpl.java:5771)
	at org.apache.calcite.sql.SqlIdentifier.accept(SqlIdentifier.java:334)
	at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:134)
	at org.apache.calcite.sql.util.SqlShuttle$CallCopyingArgHandler.visitChild(SqlShuttle.java:101)
	at org.apache.calcite.sql.SqlOperator.acceptCall(SqlOperator.java:859)
	at org.apache.calcite.sql.validate.SqlValidatorImpl$Expander.visitScoped(SqlValidatorImpl.java:5659)
	at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:50)
	at org.apache.calcite.sql.validate.SqlScopedShuttle.visit(SqlScopedShuttle.java:33)
	at org.apache.calcite.sql.SqlCall.accept(SqlCall.java:138)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.expandGroupByOrHavingExpr(SqlValidatorImpl.java:5224)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateGroupClause(SqlValidatorImpl.java:3875)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3282)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:60)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:84)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:972)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:948)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:225)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:923)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:633)
	at org.apache.flink.table.calcite.FlinkPlannerImpl.validate(FlinkPlannerImpl.scala:105)
	... 5 more
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Column 'ROWTIME' not found in table 'd'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:463)
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:572)
	... 31 more
```

分析：
在ExecuteProcessHelper::registerTable中，注册souce表字段名列表存在差异
在1.8中是：  name, channel, pv, xctime.ROWTIME,timeLeng
在1.10中是：name, channel, pv, xctime,                 timeLeng, ROWTIME.ROWTIME
差异主要是由于ExecuteProcessHelper::registerTable拼接fields字符串的方法上的差异导致，正是由于这个差异导致了袋鼠云1.8和1.10之间语法的差异，我不清楚这是你们有意为之的吗？

**Comment by todd5167** [comment]
@zhouxinhai  1.8和1.10版本FLINK时间属性是ROWTIME或者PROCTIME，你1.8版本使用TUMBLE(d.xctime, INTERVAL '1' SECOND) 应该是不对的。我这边测试的没什么问题。

1.8和1.10分支测试用的脚本：
```
CREATE TABLE MyTable(
    name varchar,
    channel varchar,
    xctime bigint,
    WATERMARK FOR xctime AS withOffset(xctime, 1000)
 )WITH(
    type ='kafka11',
    bootstrapServers ='172.16.8.107:9092',
    offsetReset ='latest',
    topic ='mqTest01',
    parallelism ='1',
    topicIsPattern='false'
 );

CREATE TABLE MyResult(
    name VARCHAR,
    cnt BIGINT,
    wStart timestamp
 )WITH(
    type ='console',
    parallelism ='1'
 );


insert
into
    MyResult
    select
        d.name,
        count(d.channel) as cnt,
        TUMBLE_START(d.ROWTIME, INTERVAL '3' SECOND) as wStart

    from
        MyTable as d 
    group by d.name,TUMBLE(d.ROWTIME, INTERVAL '3' SECOND);

```

-confProp
{\"time.characteristic\":\"eventTime\",\"sql.env.parallelism\":\"1\"}



源表数据格式：
```
{"xctime":1587375878777,"name":"mq1","channel":"ddd"}
```
