### ISSUE TITLE
执行sh命令提交任务失败

### ISSUE THREAD

**Issue by CoCoTaoLv** [DTStack/flinkStreamSQL#31]
执行提交命令 sh submit.sh -sql /home/lvtao/Desktop/sideSql.txt  -name xctest -localSqlPluginPath /home/lvtao/Desktop/flinkStreamSQL/plugins   -mode local  -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\}

出现如下错误：
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
---exeSql---
INSERT INTO MYRESULT
(SELECT D.CHANNEL, D.INFO
FROM (SELECT A.*, B.INFO
FROM MYTABLE AS A
INNER JOIN SIDETABLE AS B ON A.CHANNEL = B.NAME
WHERE A.CHANNEL = 'xc2' AND A.PV = 10) AS D)
-----------------
Connected to JobManager at Actor[akka://flink/user/jobmanager_1#-1731457055] with leader session id 93f0d7c4-ebe1-404e-94b9-5e61290438ff.
Exception in thread "main" org.apache.flink.runtime.client.JobSubmissionException: Could not retrieve BlobServer address.
        at org.apache.flink.runtime.client.JobSubmissionClientActor$1.call(JobSubmissionClientActor.java:166)
        at akka.dispatch.Futures$$anonfun$future$1.apply(Future.scala:97)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
        at org.apache.flink.runtime.client.JobSubmissionClientActor$1.call(JobSubmissionClientActor.java:160)

**Comment by CoCoTaoLv** [comment]
你好，我想知道sideSql.txt文件里面的ip都是要更改为对应的自己机器的kafka服务机器ip是的吧

**Comment by CoCoTaoLv** [comment]
我用ide直接编译，出现下面的错误：这个是不是flink的集群信息不对，连接不到服务，我应该在哪个文件修改ip，请指教，谢谢！
Connected to the target VM, address: '127.0.0.1:62596', transport: 'socket'
Disconnected from the target VM, address: '127.0.0.1:62596', transport: 'socket'
Exception in thread "main" java.lang.NullPointerException: parameters of sql is required
	at org.apache.flink.calcite.shaded.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at com.dtstack.flink.sql.Main.main(Main.java:126)

Process finished with exit code 1

**Comment by zoudaokoulife** [comment]
1：Exception in thread "main" java.lang.NullPointerException: parameters of sql is required
你用ide运行的话需要添加一些运行参数(Program arguments) 参考运行脚本；

2：sideSql.txt 是测试用例。里面的具体参数信息需要根据你自己的环境填写

**Comment by CoCoTaoLv** [comment]
请问运行脚本是submit.sh文件吗？打包在集群上面为什么不行呢？

**Comment by CoCoTaoLv** [comment]
你好，我这边打包放到集群上面运行脚本命令 sh test.sh -sql /home/hadoop/flink-1.5.2/sideSql.txt  -name flinkStreamSQL -remoteSqlPluginPath /home/hadoop/flink-1.5.2/lib/plugins   -localSqlPluginPath /home/hadoop/flink-1.5.2/lib/plugins -mode standalone -flinkconf /home/hadoop/flink-1.5.2/conf -confProp {"time.characteristic":"EventTime","sql.checkpoint.interval":10000}
sql submit ...

[root@spark-cluster-1 bin]# tail nohup.out 
Error: Could not find or load main class .home.hadoop.flink-1.5.2.lib.flink-python_2.11-1.5.2.jar


请问一下这个lib下面是需要什么文件，加载的机制是什么样的，需不需要装Hadoop客户端？谢谢

**Comment by yangsishu** [comment]
flink 的lib下的包默认是不全的，是需要你自己到网上下载下来放到lib下,
flink-metrics-prometheus-1.6.1.jar
flink-table_2.11-1.5.4.jar
flink-shaded-hadoop2-uber-1.5.4.jar
flink-python_2.11-1.5.4.jar
flink-dist_2.11-1.5.4.jar
slf4j-log4j12-1.7.7.jar
log4j-1.2.17.jar

**Comment by CoCoTaoLv** [comment]
您说的这些包跟flink的版本也有关系的吧。
我的flink-1.5.2下面的lib有部分的包：
 flink-dist_2.11-1.5.2.jar
 flink-python_2.11-1.5.2.jar
 flink-shaded-hadoop2-uber-1.5.2.jar
 log4j-1.2.17.jar
 plugins
 slf4j-log4j12-1.7.7.jar
 sql.launcher-1.0-SNAPSHOT.jar

但是报错是：
[root@spark-cluster-1 bin]# tail nohup.out
Error: Could not find or load main class .home.hadoop.flink-1.5.2.lib.flink-python_2.11-1.5.2.jar

**Comment by zoudaokoulife** [comment]
把你的test.sh 脚本内容贴出来看下

**Comment by CoCoTaoLv** [comment]
我用submit脚本运行一直报脚本有异常结束行，我就把内容放到新建的test里面来运行了，内容粘贴进去的，没有改动

set -e

export SQL_HOME="$(cd "`dirname "$0"`"/..; pwd)"

# Find the java binary
if [ -n "${JAVA_HOME}" ]; then
  JAVA_RUN="${JAVA_HOME}/bin/java"
else
  if [ `command -v java` ]; then
    JAVA_RUN="java"
  else
    echo "JAVA_HOME is not set" >&2
    exit 1
  fi
fi

JAR_DIR=$SQL_HOME/lib/*
CLASS_NAME=com.dtstack.flink.sql.launcher.LauncherMain

echo "sql submit ..."
nohup $JAVA_RUN -cp $JAR_DIR $CLASS_NAME $@ &
