### ISSUE TITLE
本地测试环境跑，提交脚本报错

### ISSUE THREAD

**Issue by Yangxu1990** [DTStack/flinkStreamSQL#317]
`sh submit.sh -sql /Users/masteryang/Documents/代码/flinkStreamSQL/flink_sql_test/flinksql.txt \
-name xctest  \
-remoteSqlPluginPath /Users/masteryang/Documents/代码/flinkStreamSQL/plugins \
-localSqlPluginPath /Users/masteryang/Documents/代码/flinkStreamSQL/plugins \
-flinkconf /Users/masteryang/Documents/代码/flinkStreamSQL/conf/flink-conf.yaml \`

flinkconf 配置了 rest.port: 8085  还是报错

`Exception in thread "main" org.apache.flink.util.FlinkException: Could not create the DispatcherResourceManagerComponent.
	at org.apache.flink.runtime.entrypoint.component.AbstractDispatcherResourceManagerComponentFactory.create(AbstractDispatcherResourceManagerComponentFactory.java:257)
	at org.apache.flink.runtime.minicluster.MiniCluster.createDispatcherResourceManagerComponents(MiniCluster.java:386)
	at org.apache.flink.runtime.minicluster.MiniCluster.start(MiniCluster.java:321)
	at com.dtstack.flink.sql.environment.MyLocalStreamEnvironment.execute(MyLocalStreamEnvironment.java:118)
	at com.dtstack.flink.sql.Main.main(Main.java:44)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:87)
Caused by: java.net.BindException: Could not start rest endpoint on any port in port range 8081
	at org.apache.flink.runtime.rest.RestServerEndpoint.start(RestServerEndpoint.java:219)
	at org.apache.flink.runtime.entrypoint.component.AbstractDispatcherResourceManagerComponentFactory.create(AbstractDispatcherResourceManagerComponentFactory.java:161)
`

**Comment by FlechazoW** [comment]
本地任务管理器查看一下，应该是有遗留的java进程。
