### ISSUE TITLE
flink集群上面提交提示这个报错

### ISSUE THREAD

**Issue by 1964305774** [DTStack/flinkStreamSQL#331]
org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot load user class: com.dtstack.flink.sql.source.kafka.KafkaConsumer010
ClassLoader info: URL ClassLoader:
    file: '/tmp/blobStore-dd4fe0b4-6a39-4861-a8df-23e15edff435/job_c9083b2bd69fb054f32ec09a355bc42b/blob_p-7889a2fe7bceb057b33c276d297c5ad5f0b159d0-945f7d983ebb50b43255ffba6b539cc7' (valid JAR)
Class not resolvable through given classloader.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:236)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:104)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:267)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.dtstack.flink.sql.source.kafka.KafkaConsumer010
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:129)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:78)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)

**Comment by lijianfeng6666526** [comment]
我也是报这个错，你解决了没？

**Comment by 1964305774** [comment]
没有呢

**Comment by k7gxn56** [comment]
现在有解决吗? 我是获取DistributedCache中的jar路径，然后进行类加载并创建UDF是报这个
