### ISSUE TITLE
> 现在不支持权限的配置

### ISSUE THREAD

**Issue by hewenxin1234** [DTStack/flinkStreamSQL#341]
> 现在不支持权限的配置
@yangsishu 
配置了es，无权限的，es版本5.6.14，运行报如下错误，请问是什么问题？
`java.lang.RuntimeException: Elasticsearch client is not connected to any Elasticsearch nodes!
at org.apache.flink.streaming.connectors.elasticsearch5.Elasticsearch5ApiCallBridge.createClient(Elasticsearch5ApiCallBridge.java:82)
at org.apache.flink.streaming.connectors.elasticsearch.ElasticsearchSinkBase.open(ElasticsearchSinkBase.java:287)
at com.dtstack.flink.sql.sink.elasticsearch.MetricElasticsearchSink.open(MetricElasticsearchSink.java:49)
at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:420)
at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:296)
at org.apache.flink.runtime.taskmanager.Task.run(Task.java:712)
at java.lang.Thread.run(Thread.java:748)
05/30/2019 11:08:34 Job execution switched to status FAILING.
`

_Originally posted by @gangly in https://github.com/DTStack/flinkStreamSQL/issues/125#issuecomment-497185987_

**Comment by hewenxin1234** [comment]
大神这个解决的方法是什么
