### ISSUE TITLE
HBase维表关联报异常：java.lang.ClassCastException: org.apache.flink.table.dataformat.GenericRow cannot be cast to org.apache.flink.types.Row

### ISSUE THREAD

**Issue by junzizai** [DTStack/flinkStreamSQL#393]
**1.10分支**

完整sql：
CREATE TABLE flink_source(
    id varchar,
    company varchar,
    nature varchar
 )WITH(
    type ='kafka11',
    bootstrapServers ='192.168.85.129:9092',
    zookeeperQuorum ='192.168.85.129:2181/kafka',
    offsetReset ='earliest',
    topic ='flink_source',
    groupId='test',
    parallelism ='1',
    timezone='Asia/Shanghai',
    sourcedatanature ='dt_nest'
 );
 
  CREATE TABLE dept(
     info:id varchar as id,
     info:name varchar as name,
     info:address varchar as address,
     PRIMARY KEY(id),
     PERIOD FOR SYSTEM_TIME
  )WITH(
     type ='hbase',
     zookeeperQuorum ='192.168.85.129:2181',
     zookeeperParent ='/hbase',
     tableName ='settle:dept',
     cache ='LRU',
     cacheSize ='10000',
     cacheTTLMs ='60000',
     parallelism ='1',
     partitionedJoin='false'
  );
 
 CREATE TABLE flink_sink(
    id varchar,
   company varchar,
   address varchar,
   nature varchar
 )WITH(
    type ='kafka11',
    bootstrapServers ='192.168.85.129:9092',
    zookeeperQuorum ='192.168.85.129:2181/kafka',
    offsetReset ='earliest',
    topic ='flink_sink',
    groupId='test',
    parallelism ='1',
    timezone='Asia/Shanghai',
    sourcedatanature ='dt_nest'
 );

insert into flink_sink
select a.id,
	a.company,
	b.address,
	a.nature
from flink_source a
 join dept b 
 on a.id=b.id;

报错异常：
java.lang.ClassCastException: org.apache.flink.table.dataformat.GenericRow cannot be cast to org.apache.flink.types.Row
	at org.apache.flink.api.java.typeutils.runtime.RowSerializer.copy(RowSerializer.java:44)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:639)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:616)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:596)
	at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:53)
	at org.apache.flink.streaming.api.operators.async.queue.StreamRecordQueueEntry.emitResult(StreamRecordQueueEntry.java:65)
	at org.apache.flink.streaming.api.operators.async.queue.OrderedStreamElementQueue.emitCompletedElement(OrderedStreamElementQueue.java:71)
	at org.apache.flink.streaming.api.operators.async.AsyncWaitOperator.outputCompletedElement(AsyncWaitOperator.java:279)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.run(StreamTaskActionExecutor.java:87)
	at org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:78)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMail(MailboxProcessor.java:261)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:186)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:485)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:469)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:708)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:533)
	at java.lang.Thread.run(Thread.java:748)

**Comment by FlechazoW** [comment]
这个问题我本地验证了，我自己的hbase demo是完全可以的，不存在baseRow转化异常问题。建议检查下Flink相关lib下的jar包，是不是使用的版本不对。

**Comment by FlechazoW** [comment]
附上我自己的demo
`-- source
CREATE  TABLE  SourceOne  (
  id  varchar
  , name varchar
  , money decimal
  , birth timestamp
  , age bigint
  , qq varchar
  , wechat varchar
  , phone varchar
  , todayTime time AS createTime
) WITH  (
    type ='kafka11',
    bootstrapServers ='localhost:9092',
    zookeeperQuorum ='localhost:2181',
    offsetReset ='latest',
    topic ='tiezhu_in',
    enableKeyPartitions ='false',
    topicIsPattern ='false',
    parallelism ='1'
);

-- side One
CREATE TABLE SideOne(
  stu:id varchar as sid
  , stu:phone varchar as sphone
  , stu:name VARCHAR AS name
  , stu:qq varchar as sqq
  , stu:wechat varchar as swechat
  , stu:income varchar as income
  , stu:birthday varchar as birthday
  , stu:today varchar as today
  , stu:timecurrent varchar as timecurrent
  , info:qq varchar AS iqq
  , info:wechat varchar AS iwechat
  , PRIMARY  KEY  ('stu'+'_'+sid+'_'+md5(sid))
  , PERIOD  FOR  SYSTEM_TIME
) WITH  (
    type = 'hbase',
    zookeeperQuorum ='ss01,ss02,ss03',
    zookeeperParent ='/hbase',
    tableName ='tiezhuDemoTwo',
	partitionedJoin ='false',
	parallelism ='1',
	cache = 'LRU'
);

-- side one
CREATE TABLE SinkOne(
  sid varchar as sid
  , sphone varchar as sphone
  , name VARCHAR AS name
  , sqq varchar as sqq
  , swechat varchar as swechat
  , income decimal as income
  , birthday timestamp as birthday
  , today date as today
  , timecurrent time as timecurrent
  , iqq varchar AS iqq
  , iwechat varchar AS iwechat
) WITH (
    type = 'console',
    zookeeperQuorum ='ss01,ss02,ss03',
    zookeeperParent ='/hbase',
    tableName ='tiezhuDemoThree',
	partitionedJoin ='false',
	parallelism ='1',
	rowKey = ''stu'+'_'+sid+'_'+md5(sid)'
);

-- view
CREATE VIEW ViewOne AS
SELECT
    SO2.sid AS sid
    , cast(SO2.today AS date) AS today
    , cast(SO2.timecurrent AS time) AS timecurrent
    , SO.birth AS birthday
    , SO.money AS income
    , SO.phone AS sphone
    , SO.qq AS sqq
    , SO.wechat AS swechat
    , SO2.name AS name
    , SO2.sqq AS iqq
    , SO2.iwechat AS iwechat
FROM SourceOne SO
LEFT JOIN SideOne SO2 on SO.id = SO2.sid ;

INSERT INTO SinkOne
SELECT * FROM ViewOne;`

**Comment by junzizai** [comment]
能不能麻烦你截图给我看下你lib目录下的依赖包版本呢

**Comment by FlechazoW** [comment]
就是正常的apache flink 1.10.1的包。

**Comment by a49a** [comment]
Flink 版本要对齐 1.10.1就必须得是 1.10.1
