### ISSUE TITLE
Standalone模式报错

### ISSUE THREAD

**Issue by Feral-Jas** [DTStack/flinkStreamSQL#398]
`Exception in thread "main" java.lang.RuntimeException: Couldn't retrieve standalone cluster
        at org.apache.flink.client.deployment.StandaloneClusterDescriptor.lambda$retrieve$0(StandaloneClusterDescriptor.java:54)
        at com.dtstack.flink.sql.launcher.executor.StandaloneExecutor.exec(StandaloneExecutor.java:64)
        at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:149)
Caused by: java.lang.NullPointerException: rest.address must be set
        at org.apache.flink.util.Preconditions.checkNotNull(Preconditions.java:104)
        at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.getWebMonitorAddress(HighAvailabilityServicesUtils.java:188)
        at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.createClientHAService(HighAvailabilityServicesUtils.java:138)
        at org.apache.flink.client.program.rest.RestClusterClient.<init>(RestClusterClient.java:168)
        at org.apache.flink.client.deployment.StandaloneClusterDescriptor.lambda$retrieve$0(StandaloneClusterDescriptor.java:52)
        ... 2 more
Exception in thread "main" java.lang.IllegalArgumentException: standalone only supports classpath mode
        at org.apache.flink.util.Preconditions.checkArgument(Preconditions.java:139)
        at com.dtstack.flink.sql.launcher.executor.StandaloneExecutor.exec(StandaloneExecutor.java:50)
        at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:149)`

我的指令：
`sh submit.sh -mode standalone -name standalone_kafka2kafka -sql /Users/liuchenyu/Desktop/work/FlinkSqlExecutor/sql-process/kafka2kafka.sql -localSqlPluginPath /Users/liuchenyu/Desktop/work/FlinkSqlExecutor/sqlplugins -remoteSqlPluginPath /Users/liuchenyu/Desktop/work/FlinkSqlExecutor/sqlplugins
 -flinkconf /usr/local/Cellar/apache-flink/1.11.1/libexec/conf -pluginLoadMode shipfile`

想请问一下这里对flinkconf的配置是不是也有要求，看起来是去读flink-conf里的配置，而且要求一些字段必须非空

**Comment by Feral-Jas** [comment]
已解决：pluginLoadMode=classpath，standalone模式支持classpath
