### ISSUE TITLE
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException

### ISSUE THREAD

**Issue by marshals1995** [DTStack/flinkStreamSQL#399]
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: 
==========use flink planner ,Dim table join Please use the following sql syntax==========
CREATE VIEW view_out AS select
    u.id,
    s.name 
  FROM
    source u 
  LEFT JOIN
    side FOR SYSTEM_TIME AS OF u.PROCTIME AS s 
      ON u.id = s.sid;
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:302)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:198)
	at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:150)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:77)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:109)
	at com.dtstack.flink.sql.launcher.utils.JobGraphBuildUtil.buildJobGraph(JobGraphBuildUtil.java:80)
	at com.dtstack.flink.sql.launcher.executor.StandaloneExecutor.exec(StandaloneExecutor.java:53)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:149)
	at com.dtstack.flink.sql.launcher.PluginLoadModeTest.KafkaToMysql03(PluginLoadModeTest.java:116)
	at com.dtstack.flink.sql.launcher.PluginLoadModeTest.main(PluginLoadModeTest.java:162)
Caused by: com.dtstack.flink.sql.exception.sqlparse.PlannerNotMatchException: 
==========use flink planner ,Dim table join Please use the following sql syntax==========
CREATE VIEW view_out AS select
    u.id,
    s.name 
  FROM
    source u 
  LEFT JOIN
    side FOR SYSTEM_TIME AS OF u.PROCTIME AS s 
      ON u.id = s.sid;
	at com.dtstack.flink.sql.Main.main(Main.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:288)
	... 9 more

**Comment by skypan** [comment]
i meet the same problem, How can you resolve it ?
