### ISSUE TITLE
Standalone模式提交怎么会调用异常？

### ISSUE THREAD

**Issue by jiaenqiu** [DTStack/flinkStreamSQL#402]
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: Could not run job in detached mode. (JobID: bda69dcfcf4c7257870f762a0230c40d)
 at org.apache.flink.client.ClientUtils.submitJob(ClientUtils.java:88)
 at com.dtstack.flink.sql.launcher.executor.StandaloneExecutor.exec(StandaloneExecutor.java:67)
 at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:149)
Caused by: java.util.concurrent.ExecutionException: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
 at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
 at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
 at org.apache.flink.client.ClientUtils.submitJob(ClientUtils.java:85)

**Comment by Feral-Jas** [comment]
是不是没写classpath，只有yarn集群支持ship file，之前也遇到过这个问题

**Comment by FlechazoW** [comment]
需要有完整的报错信息，这部分信息看不出具体问题的。
