### ISSUE TITLE
Unknown database 'flinktest'  ,明明是有这个 库, 为何最好老是说不存在?

### ISSUE THREAD

**Issue by ithjz** [DTStack/flinkStreamSQL#413]
userName: root
error message: Unknown database 'flinktest'
17:47:04.156 [main] WARN com.dtstack.flink.sql.core.rdb.util.JdbcConnectUtil - 
Connect will retry after [3] s. Retry time [3] ...
Exception in thread "main" org.apache.flink.runtime.execution.SuppressRestartsException: Unrecoverable failure. 
This suppresses job restarts. Please check the stack trace for the root cause.
	at com.dtstack.flink.sql.core.rdb.util.JdbcConnectUtil.getConnectWithRetry(JdbcConnectUtil.java:158)
	at com.dtstack.flink.sql.core.rdb.JdbcResourceCheck.checkPrivilege(JdbcResourceCheck.java:112)
	at com.dtstack.flink.sql.core.rdb.JdbcResourceCheck.checkResourceStatus(JdbcResourceCheck.java:87)
	at com.dtstack.flink.sql.sink.rdb.table.RdbTableInfo.check(RdbTableInfo.java:213)
	at com.dtstack.flink.sql.sink.rdb.table.RdbSinkParser.getTableInfo(RdbSinkParser.java:56)
	at com.dtstack.flink.sql.sink.mysql.table.MysqlSinkParser.getTableInfo(MysqlSinkParser.java:42)
	at com.dtstack.flink.sql.table.AbstractTableInfoParser.parseWithTableType(AbstractTableInfoParser.java:129)
	at com.dtstack.flink.sql.parser.SqlParser.parseSql(SqlParser.java:145)
	at com.dtstack.flink.sql.exec.ExecuteProcessHelper.getStreamExecution(ExecuteProcessHelper.java:201)
	at com.dtstack.flink.sql.Main.main(Main.java:47)
	at com.dtstack.flink.sql.localTest.LocalTest.main(LocalTest.java:86)
Caused by: java.lang.Throwable: 
Get connect failed with properties: 
url: jdbc:mysql://192.168.1.121:3306/flinktest?charset=utf8
userName: root
error message: Unknown database 'flinktest'
	... 11 more

**Comment by ithjz** [comment]
type= 'mysql',
    url = 'jdbc:mysql://192.168.1.121:3306/flinktest?charset=utf8',
    tableName = 'pvuv_sink',
    username= 'root',
