### ISSUE TITLE
我win10本地运行  ,读kafka写kafka  ,咋就没有这个呢? com.dtstack.flink.sql.sink.kafka.table.KafkaSinkParser

### ISSUE THREAD

**Issue by ithjz** [DTStack/flinkStreamSQL#417]
我win10本地运行  ,读kafka写kafka  ,咋就没有这个呢? com.dtstack.flink.sql.sink.kafka.table.KafkaSinkParser

KafkaSinkParser,

Exception in thread "main" java.lang.ClassNotFoundException: com.dtstack.flink.sql.sink.kafka.table.KafkaSinkParser
	at com.dtstack.flink.sql.classloader.DtClassLoader.loadClass(DtClassLoader.java:137)
	at com.dtstack.flink.sql.classloader.DtClassLoader.loadClass(DtClassLoader.java:71)
	at com.dtstack.flink.sql.sink.StreamSinkFactory.lambda$getSqlParser$0(StreamSinkFactory.java:49)
	at com.dtstack.flink.sql.classloader.ClassLoaderSupplierCallBack.callbackAndReset(ClassLoaderSupplierCallBack.java:33)
	at com.dtstack.flink.sql.classloader.ClassLoaderManager.newInstance(ClassLoaderManager.java:77)
	at com.dtstack.flink.sql.sink.StreamSinkFactory.getSqlParser(StreamSinkFactory.java:48)
	at com.dtstack.flink.sql.table.AbstractTableInfoParser.parseWithTableType(AbstractTableInfoParser.java:116)
	at com.dtstack.flink.sql.parser.SqlParser.parseSql(SqlParser.java:146)
	at com.dtstack.flink.sql.exec.ExecuteProcessHelper.getStreamExecution(ExecuteProcessHelper.java:201)
	at com.dtstack.flink.sql.Main.main(Main.java:47)
	at com.dtstack.flink.sql.localTest.LocalTest.main(LocalTest.java:87)
18:26:12.850 [main] WARN com.dtstack.flink.sql.util.PluginUtil - be sure you are not in LocalTest mode, if not, check the sqlRootDir
18:26:12.851 [main] INFO com.dtstack.flink.sql.classloader.ClassLoaderManager - pluginJarPath:null\kafka11sink create ClassLoad successful...

**Comment by ithjz** [comment]
maven编译 出错了,[ERROR] Failed to execute goal on project sql.source.kafka11:
 Could not resolve dependencies for project com.dtstack.flink:sql.source.kafka11:jar:1.0-SNAPSHOT: 
 The following artifacts could not be resolved: com.dtstack.flink:sql.source.kafka-base:jar:1.0-SNAPSHOT,
 com.dtstack.flink:sql.core:jar:1.0-SNAPSHOT: Failure to find com.dtstack.flink:sql.source.kafka-base:jar:1.0-SNAPSHOT 
 in  was cached in the local repository,
 resolution will not be reattempted until the update interval of   maven-source has elapsed or updates are forced -> [Help 1]
[ERROR]               


KafkaSink  报错了

**Comment by FlechazoW** [comment]
1. localTest 模块下只有kafka11的依赖，如果使用其他的，自己去修改即可；
2. 这个maven编译报错，百度一下就有解决方案。把maven 仓库下，对应路径下的lastUpdated文件删除，之后再重新maven package即可；
