### ISSUE TITLE
多次提交任务时报KafkaSourceTableInfo类型转换错误

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#49]
我在原先项目中加了netty，把服务包装成可以rest请求提交的形式，每次被请求时就调Launcher里的LauncherMain.main方法提交任务。但是首次提交任务时成功，再次提交后就报如下错误：

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:542)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:417)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:396)
	at com.dtstack.flink.sql.launcher.LauncherMain.submit(LauncherMain.java:91)
	at com.dtstack.flink.sql.launcher.httpserver.NettyHttpServer$HttpHandler$1.run(NettyHttpServer.java:228)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: com.dtstack.flink.sql.source.kafka.table.KafkaSourceTableInfo cannot be cast to com.dtstack.flink.sql.source.kafka.table.KafkaSourceTableInfo
	at com.dtstack.flink.sql.source.kafka.KafkaSource.genStreamSource(KafkaSource.java:56)
	at com.dtstack.flink.sql.source.kafka.KafkaSource.genStreamSource(KafkaSource.java:44)
	at com.dtstack.flink.sql.source.StreamSourceFactory.getStreamSource(StreamSourceFactory.java:90)
	at com.dtstack.flink.sql.Main.registerTable(Main.java:247)
	at com.dtstack.flink.sql.Main.main(Main.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:525)
	... 5 more

**Comment by yangsishu** [comment]
你现在用的是什么版本的

**Comment by nuaabuaa07** [comment]
请问，我看分支有1.6了，这个分支是支持flink1.6了吗？

**Comment by yangsishu** [comment]
是的，这个是有其他的开发者做了flink1.6的兼容测试，我们还没把最新的代码合并到1.6上
