### ISSUE TITLE
flink集群提交job报错Caused by: java.util.concurrent.CompletionException: org.apache.flink.client.program.ProgramInvocationException: The program plan could not be fetched - the program aborted pre-maturely.

### ISSUE THREAD

**Issue by zhouluoyang0406** [DTStack/flinkStreamSQL#80]
System.err: ---exeSql---
INSERT INTO `tb_target`
(SELECT `c`.`id`, `c`.`username`, `d`.`deptname`, `d`.`description`, `c`.`posname`, `c`.`money`, `c`.`__event_type`, `c`.`__timestamp`
FROM (SELECT `b`.`id` AS `id`, `b`.`deptid`, `b`.`username`, `a`.`posname`, `a`.`money`, `a`.`__timestamp`, `a`.`__event_type`
FROM `tb_pos_curr` AS `a`
INNER JOIN `tb_emp` AS `b` ON `b`.`posid` = `a`.`id`) AS `c`
INNER JOIN `tb_dept` AS `d` ON `d`.`id` = `c`.`deptid`)
---------side_exe_sql-----
select id,deptid,posid,username from tb_emp where posid=?
-----------------
---------side_exe_sql-----
select id,deptname,description from tb_dept where id=?
-----------------
---submit end----

System.out: (none)
	at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$7(JarRunHandler.java:151)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CompletionException: org.apache.flink.client.program.ProgramInvocationException: The program plan could not be fetched - the program aborted pre-maturely.

flink提交任务不能返回jobid，但是能够成功运行。如果需要提供别的什么资料请回复。十分感谢。

**Comment by zhouluoyang0406** [comment]
-sql
/Users/zhouluoyang/Desktop/dataSupport/data/project/flinkSteamSql/bin/tb_pos.txt
-name
xctest
-mode
local
-localSqlPluginPath
/Users/zhouluoyang/Desktop/dataSupport/data/project/flinkSteamSql/plugins
-confProp
{\"time.characteristic\":\"ProcessingTime\",\"sql.checkpoint.interval\":10000}

**Comment by yangsishu** [comment]
flink用的什么版本

**Comment by yangsishu** [comment]
还有这个框架你用的是那个分支

**Comment by zhouluoyang0406** [comment]
@yangsishu  flink 1.6。分支是1.5。不能使用flink 1.6的是么？

**Comment by zhouluoyang0406** [comment]
@yangsishu   非常感谢 我试一试
