### ISSUE TITLE
请问，flinkStreamSQL 1.6.0_release Jobmanager 连接超时，有遇到过吗？怎么解决？

### ISSUE THREAD

**Issue by Yimin-Liu** [DTStack/flinkStreamSQL#85]
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: The program execution failed: JobManager did not respond within 60000 ms (JobID: d4cfc96ea9bf00c66083221bb2a3a049)
	at org.apache.flink.client.program.ClusterClient.runDetached(ClusterClient.java:556)
	at org.apache.flink.client.program.StandaloneClusterClient.submitJob(StandaloneClusterClient.java:117)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:486)
	at org.apache.flink.client.program.DetachedEnvironment.finalizeExecute(DetachedEnvironment.java:77)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:432)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:86)
Caused by: org.apache.flink.runtime.client.JobTimeoutException: JobManager did not respond within 60000 ms
	at org.apache.flink.runtime.client.JobClient.submitJobDetached(JobClient.java:438)
	at org.apache.flink.client.program.ClusterClient.runDetached(ClusterClient.java:547)
	... 5 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.apache.flink.runtime.client.JobClient.submitJobDetached(JobClient.java:436)
	... 6 more

**Comment by ssyue** [comment]
+1

**Comment by Domn93** [comment]
1.7的+1

**Comment by lycbug666** [comment]
@Domn93 master分支代码 1.5.4 +1

**Comment by hjfhjf** [comment]
+1

**Comment by lycbug666** [comment]
目前发现是 jar 包依赖的问题，去掉 yarn 的依赖可以正常提交。
