### ISSUE TITLE
本地测试输出hbase sink报log4j错误

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#86]
java.lang.NoClassDefFoundError: org/apache/log4j/Level
	at org.apache.hadoop.mapred.JobConf.<clinit>(JobConf.java:354)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:1834)
	at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:91)
	at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:75)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:133)
	at org.apache.hadoop.security.Groups.<init>(Groups.java:64)
	at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:240)
	at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:225)
	at org.apache.hadoop.hbase.security.UserProvider.<clinit>(UserProvider.java:56)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:214)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
	at com.dtstack.flink.sql.sink.hbase.HbaseOutputFormat.open(HbaseOutputFormat.java:81)
	at org.apache.flink.streaming.api.functions.sink.OutputFormatSinkFunction.open(OutputFormatSinkFunction.java:64)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:424)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:290)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more

**Comment by yangsishu** [comment]
那个版本

**Comment by yangsishu** [comment]
@zoudaokoulife 看下

**Comment by nuaabuaa07** [comment]
是1.6release版本

**Comment by nuaabuaa07** [comment]
你好，请问，这个bug修复了吗

**Comment by oOKevinOo** [comment]
com.dtstack.flink.sql.launcher.LauncherMain主类提交不会有该问题吧，com.dtstack.flink.sql.Main类提交才会有这个问题

**Comment by AccordwangAccord** [comment]
@yangsishu [大牛请问一下]
Caused by: java.lang.RuntimeException: class org.apache.hadoop.yarn.client.ConfiguredRMFailoverProxyProvider not org.apache.hadoop.yarn.client.RMFailoverProxyProvider
这个怎么解决 我用的是master版本 hbasesink冲突了
