### ISSUE TITLE
如何定义一个WATERMARK

### ISSUE THREAD

**Issue by oOKevinOo** [DTStack/flinkStreamSQL#88]
我测试了一个socket demo，sql如下：
CREATE TABLE socket_data(
    channel varchar,
    pv int,
    xctime date,
    xtime timestamp,
    WATERMARK FOR xtime AS withOffset( xtime , 2000 )
 )WITH(
    type='serversocket',
    host='192.168.15.41',
    port='19888',
    delimiter=';',
    maxNumRetries='100'
 );
CREATE TABLE MyResult(
    channel VARCHAR,
    time timestamp,
    pv int
 )WITH(
    type ='mysql',
    url ='jdbc:mysql://xxx.xxx.xx.xx:3306/streaming?charset=utf8',
    userName ='root',
    password ='123456',
    tableName ='sock_pv',
    parallelism ='1'
 );
insert into MyResult
    select
        channel,
        TUMBLE_START(xtime, INTERVAL '1' MINUTE) as p_time,
        sum(pv) as s_pv
    from socket_data group by TUMBLE(xtime, INTERVAL '1' MINUTE),channel;

但启动返回错误如下（原因是定义的WATERMARK不存在）：
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:546)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:421)
	at org.apache.flink.client.program.OptimizerPlanEnvironment.getOptimizedPlan(OptimizerPlanEnvironment.java:83)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:78)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:120)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:82)
Caused by: org.apache.flink.table.api.ValidationException: Window can only be defined over a time attribute column.
	at org.apache.flink.table.api.ValidationException$.apply(exceptions.scala:75)
	at org.apache.flink.table.plan.rules.datastream.DataStreamLogicalWindowAggregateRule.getOperandAsTimeIndicator$1(DataStreamLogicalWindowAggregateRule.scala:82)
	at org.apache.flink.table.plan.rules.datastream.DataStreamLogicalWindowAggregateRule.translateWindowExpression(DataStreamLogicalWindowAggregateRule.scala:87)
	at org.apache.flink.table.plan.rules.common.LogicalWindowAggregateRule.onMatch(LogicalWindowAggregateRule.scala:65)
	at org.apache.calcite.plan.AbstractRelOptPlanner.fireRule(AbstractRelOptPlanner.java:317)
	at org.apache.calcite.plan.hep.HepPlanner.applyRule(HepPlanner.java:556)
	at org.apache.calcite.plan.hep.HepPlanner.applyRules(HepPlanner.java:415)
	at org.apache.calcite.plan.hep.HepPlanner.executeInstruction(HepPlanner.java:252)
	at org.apache.calcite.plan.hep.HepInstruction$RuleInstance.execute(HepInstruction.java:127)
	at org.apache.calcite.plan.hep.HepPlanner.executeProgram(HepPlanner.java:211)
	at org.apache.calcite.plan.hep.HepPlanner.findBestExp(HepPlanner.java:198)
	at org.apache.flink.table.api.TableEnvironment.runHepPlanner(TableEnvironment.scala:257)
	at org.apache.flink.table.api.StreamTableEnvironment.optimize(StreamTableEnvironment.scala:827)
	at org.apache.flink.table.api.StreamTableEnvironment.translate(StreamTableEnvironment.scala:892)
	at org.apache.flink.table.api.StreamTableEnvironment.writeToSink(StreamTableEnvironment.scala:344)
	at org.apache.flink.table.api.TableEnvironment.insertInto(TableEnvironment.scala:784)
	at org.apache.flink.table.api.TableEnvironment.sqlUpdate(TableEnvironment.scala:722)
	at org.apache.flink.table.api.TableEnvironment.sqlUpdate(TableEnvironment.scala:682)
	at com.dtstack.flink.sql.Main.main(Main.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:529)
	... 5 more
如果按原flink格式定义WATERMARK的话报错如下：
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:546)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:421)
	at org.apache.flink.client.program.OptimizerPlanEnvironment.getOptimizedPlan(OptimizerPlanEnvironment.java:83)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:78)
	at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:120)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:82)
Caused by: java.lang.RuntimeException: 不支持 ) 类型
	at com.dtstack.flink.sql.util.ClassUtil.stringConvertClass(ClassUtil.java:74)
	at com.dtstack.flink.sql.table.AbsTableParser.parseFieldsInfo(AbsTableParser.java:102)
	at com.dtstack.flink.sql.source.serversocket.table.ServersocketSourceParser.getTableInfo(ServersocketSourceParser.java:38)
	at com.dtstack.flink.sql.table.TableInfoParser.parseWithTableType(TableInfoParser.java:104)
	at com.dtstack.flink.sql.parser.SqlParser.parseSql(SqlParser.java:115)
	at com.dtstack.flink.sql.Main.main(Main.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:529)

启动命令为：
bin/submit.sh -sql /usr/local/workspace/flinkStreamSQL-1.6.0/sqls/socket_test.txt  -name xctest -remoteSqlPluginPath /usr/local/workspace/flinkStreamSQL-1.6.0/plugins   -localSqlPluginPath /usr/local/workspace/flinkStreamSQL-1.6.0/plugins  -mode yarnPer -flinkconf /usr/local/workspace/flink-1.6.1/conf -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\}

**Comment by yangsishu** [comment]
用的是那个分支

**Comment by oOKevinOo** [comment]
flink 1.6.1
flinkStreamSQL 1.6.0 release

**Comment by yangsishu** [comment]
insert into MyResult
select
channel,
TUMBLE_START(ROWTIME, INTERVAL '1' MINUTE) as p_time,
sum(pv) as s_pv
from socket_data group by TUMBLE(ROWTIME, INTERVAL '1' MINUTE),channel;

**Comment by yangsishu** [comment]
这个就是flink的格式

**Comment by oOKevinOo** [comment]
有个关于kafka的问题想请教下，我的配置如下：
CREATE TABLE kafka_data(
 channel varchar,
    pv int,
    xctime date,
    xtime timestamp,
    WATERMARK FOR xtime AS withOffset( xtime , 1000 )
 )WITH(
    type ='kafka10',
    kafka.bootstrap.servers ='host1:6667',
    kafka.zookeeper.quorum ='host1:2181',
    kafka.auto.offset.reset ='latest',
    kafka.topic ='flink_test',
    parallelism ='3',
    --timezone='America/Los_Angeles',
    timezone='Asia/Shanghai',
    sourcedatatype ='json' #可不设置
 );
CREATE TABLE MyResult(
    channel VARCHAR,
    time timestamp,
    pv int
 )WITH(
    type ='mysql',
    url ='jdbc:mysql://xxx.xxx.xx.xxx:3306/streaming?charset=utf8',
    userName ='root',
    password ='123456',
    tableName ='sock_pv',
    parallelism ='1'
 );
 
insert into MyResult
    select
        channel,
        TUMBLE_START(ROWTIME, INTERVAL '1' MINUTE),
        sum(pv) as s_pv
    from kafka_data group by TUMBLE(ROWTIME, INTERVAL '1' MINUTE),channel;

我的环境是hdp2.6.4，kafka版本是0.10.1，生成kafka数据用的是0.10.1.0的jar，但是运行上述sql的时候报了如下错误：
java.lang.NullPointerException
	at com.dtstack.flink.sql.source.kafka.deserialization.CustomerCommonDeserialization.deserialize(CustomerCommonDeserialization.java:77)
	at com.dtstack.flink.sql.source.kafka.deserialization.CustomerCommonDeserialization.deserialize(CustomerCommonDeserialization.java:55)
	at org.apache.flink.streaming.connectors.kafka.internal.Kafka09Fetcher.runFetchLoop(Kafka09Fetcher.java:142)
	at org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumerBase.run(FlinkKafkaConsumerBase.java:738)
	at com.dtstack.flink.sql.source.kafka.consumer.CustomerCommonConsumer.run(CustomerCommonConsumer.java:68)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:87)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:56)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:99)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:745)

异常提示使用的是Kafka09Fetcher，我现在疑惑我是生成kafka数据的jar依赖选错了还是配置上错误了。kafka的版本改如何选择？

**Comment by oOKevinOo** [comment]
另外kafka生成的数据格式如下：
![image](https://user-images.githubusercontent.com/24331196/53538955-9da58580-3b4a-11e9-9234-29fbcf0b68ca.png)

**Comment by yangsishu** [comment]
你可以用local模式本地debug，
com.dtstack.flink.sql.source.kafka.deserialization.CustomerCommonDeserialization.deserialize(CustomerCommonDeserialization.java:77在这个地方断点下)

**Comment by yangsishu** [comment]
再拉下代码，空指针的报错修复了

**Comment by oOKevinOo** [comment]
我断点调试了下 空指针是kafka event的key是空值引起的，给key附上值就没抱错了，但是现在又出现了个新问题，错误如下：
java.lang.RuntimeException: Row arity of from does not match serializers.
	at org.apache.flink.streaming.runtime.io.RecordWriterOutput.pushToRecordWriter(RecordWriterOutput.java:110)
	at org.apache.flink.streaming.runtime.io.RecordWriterOutput.collect(RecordWriterOutput.java:89)
	at org.apache.flink.streaming.runtime.io.RecordWriterOutput.collect(RecordWriterOutput.java:45)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:689)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:667)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollectWithTimestamp(StreamSourceContexts.java:310)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collectWithTimestamp(StreamSourceContexts.java:409)
	at org.apache.flink.streaming.connectors.kafka.internals.AbstractFetcher.emitRecordWithTimestamp(AbstractFetcher.java:398)
	at org.apache.flink.streaming.connectors.kafka.internal.Kafka010Fetcher.emitRecord(Kafka010Fetcher.java:89)
	at org.apache.flink.streaming.connectors.kafka.internal.Kafka09Fetcher.runFetchLoop(Kafka09Fetcher.java:154)
	at org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumerBase.run(FlinkKafkaConsumerBase.java:738)
	at com.dtstack.flink.sql.source.kafka.consumer.CustomerCommonConsumer.run(CustomerCommonConsumer.java:68)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:87)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:56)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:99)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:745)


我写kafka的demo如下：
 Properties properties = new Properties();
        properties.put("bootstrap.servers", "host1:6667");
        properties.put("acks", "all");
        properties.put("retries", 0);
        properties.put("batch.size", 50);
        properties.put("linger.ms", 1);
        properties.put("buffer.memory", 33554432);
        properties.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        properties.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");
        Producer<String, String> producer = null;
        try {
            producer = new KafkaProducer<String, String>(properties);
            int count = 1;
            while (true) {
                String key = "msg " + count;
                producer.send(new ProducerRecord<String, String>("flink_test" ,key, MsgGenerator.generate()));
                System.out.println("Sented count:" + count);
                count++;
                Thread.sleep(new Random(666).nextInt(3000));
            }

        } catch (Exception e) {
            e.printStackTrace();

        } finally {
            producer.close();
        }


public class MsgGenerator {
    private static String str_format = "{\"CHANNEL\":\"xc%s\",\"pv\":%s,\"xdate\":\"2019-02-27\",\"xtime\":\"%s\"};";
    private static Random random = new Random(666);
    public static String generate() {
        return String.format(str_format,getInt(100),getInt(1000),System.currentTimeMillis());
    }
    public static int getInt(int bound) {
        return random.nextInt(bound);
    }
}


是写进kafka的序列化类引起的吗，写入kafka的序列化要用指定的序列化类还是直接用String序列化类就行？

**Comment by oOKevinOo** [comment]
用socketsource获取的数据整个流程是可以跑通的，kafka就遇到序列化问题

**Comment by oOKevinOo** [comment]
kafka的
java.lang.RuntimeException: Row arity of from does not match serializers.问题刚我debug了下，发现我在定义kafka表时加上
sourcedatatype ='json'属性的时候传进来的kafka event是原始的kafka数据，格式是这样的：
     _topic STRING,
     _messageKey STRING,
     _message STRING,
     _partition INT,
     _offset BIGINT,

当我把sourcedatatype ='json'属性给去掉的时候就正常解析json了，不会在解析原始kafka event的时候抛出runtimeException。

**Comment by oOKevinOo** [comment]
引擎异常的原因大致如下：
![image](https://user-images.githubusercontent.com/24331196/53549482-3d750a80-3b6f-11e9-8e72-b5bd69ec73fc.png)
代码定位于org.apache.flink.api.java.typeutils.runtime.RowSerializer的serialize方法
