### ISSUE TITLE
hbase-sink yarn提交问题

### ISSUE THREAD

**Issue by oOKevinOo** [DTStack/flinkStreamSQL#89]
使用hbase-sink模块时抛出如下异常：
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: class org.apache.hadoop.yarn.client.ConfiguredRMFailoverProxyProvider not org.apache.hadoop.yarn.client.RMFailoverProxyProvider
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:1927)
	at org.apache.hadoop.yarn.client.RMProxy.createRMFailoverProxyProvider(RMProxy.java:154)
	at org.apache.hadoop.yarn.client.RMProxy.createRMProxy(RMProxy.java:87)
	at org.apache.hadoop.yarn.client.ClientRMProxy.createRMProxy(ClientRMProxy.java:70)
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.serviceStart(YarnClientImpl.java:139)
	at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
	at com.dtstack.flink.sql.launcher.perjob.PerJobClusterClientBuilder.init(PerJobClusterClientBuilder.java:60)
	at com.dtstack.flink.sql.launcher.perjob.PerJobSubmitter.submit(PerJobSubmitter.java:53)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:83)

  刚开始以为是hadoop版本问题，测试集群使用的是hdp-2.6.4.0-91，对于hadoop版本为2.7.3.2.6.4.0-91，而flinkStreamSQL使用的是apache发行的hadoop版本2.5.1，通过对hbase-sink模块exclude在重新指定hadoop版本后任然报该错误。
  想问下作者是如何配置yarn.client.failover-proxy-provider参数的？

**Comment by oOKevinOo** [comment]
1.6release版本以解决该问题，主要是集群环境的hadoop版本与项目依赖的hadoop版本不兼容，暂时提交到https://github.com/oOKevinOo/flinkStreamSQL.git中，maven编译可通过-Dhadoop.version=xxx指定hadoop版本

**Comment by lixiyuan123** [comment]
> 1.6release版本以解决该问题，主要是集群环境的hadoop版本与项目依赖的hadoop版本不兼容，暂时提交到https://github.com/oOKevinOo/flinkStreamSQL.git 中，maven编译可通过-Dhadoop.version=xxx指定hadoop版本

您好我用的就是1.6的release版本，使用的Yarn_per模式提交的任务。也依然报这个错。mvn clean package -Dmaven.test.skip -Dhadoop.version=2.7.5 我是使用的如下命令编译的，您帮忙看看有什么问题？

**Comment by AccordwangAccord** [comment]
大神解决了吗?可以指导一下吗

**Comment by AccordwangAccord** [comment]
@lixiyuan123 兄弟解决了吗？麻烦告知下

**Comment by oOKevinOo** [comment]
![image](https://user-images.githubusercontent.com/24331196/62286026-6fc1c580-b489-11e9-9482-b0b6f193adf9.png)
pom里添加下这两个配置试试

**Comment by AccordwangAccord** [comment]
@oOKevinOo 
<hadoop.version>2.7.3.2.6.4.0-91</hadoop.version>
<repositories>
<repositorie>
<id>public</id>
<url>http://nexus-private.hortonworks.com/nexus/content/groups/public</url>
</repositorie>
</repositories>

<artifactId>hbase-client</artifactId>
<version>1.2.6</version>

这个是我编译的命令 mvn clean package -Dmaven.test.skip -Dhadoop.version=2.6.0
依然一样的错误

**Comment by AccordwangAccord** [comment]
@oOKevinOo 请教下大牛
上面按照你说的弄了
hbase-client的版本是1.2.6
这个是我编译的命令 mvn clean package -Dmaven.test.skip -Dhadoop.version=2.6.0

**Comment by oOKevinOo** [comment]
拉下这个代码https://github.com/oOKevinOo/flinkStreamSQL，在mvn clean package -Dmaven.test.skip编译下
