### ISSUE TITLE
1.6 standalone模式下 Failed to retrieve the JobManager gateway.

### ISSUE THREAD

**Issue by tonychen0716** [DTStack/flinkStreamSQL#92]
1.6 release版本 提交任务时报错，错误信息如下
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: Failed to retrieve the JobManager gateway. (JobID: c36f771e5369d005412cf4c7e52d462e)
	at org.apache.flink.client.program.ClusterClient.runDetached(ClusterClient.java:542)
	at org.apache.flink.client.program.StandaloneClusterClient.submitJob(StandaloneClusterClient.java:117)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:486)
	at org.apache.flink.client.program.DetachedEnvironment.finalizeExecute(DetachedEnvironment.java:77)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:432)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:87)
Caused by: org.apache.flink.util.FlinkException: Could not connect to the leading JobManager. Please check that the JobManager is running.
	at org.apache.flink.client.program.ClusterClient.getJobManagerGateway(ClusterClient.java:956)
	at org.apache.flink.client.program.ClusterClient.runDetached(ClusterClient.java:539)
	... 5 more
Caused by: org.apache.flink.runtime.leaderretrieval.LeaderRetrievalException: Could not retrieve the leader gateway.
	at org.apache.flink.runtime.util.LeaderRetrievalUtils.retrieveLeaderGateway(LeaderRetrievalUtils.java:83)
	at org.apache.flink.client.program.ClusterClient.getJobManagerGateway(ClusterClient.java:951)
	... 6 more
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at scala.concurrent.Await.result(package.scala)
	at org.apache.flink.runtime.util.LeaderRetrievalUtils.retrieveLeaderGateway(LeaderRetrievalUtils.java:81)
	... 7 more

flink standalone集群环境采用官方提供的docker镜像，采用传统的jar包界面提交方式，可以正常提交和执行
docker-compose.yml

 jobmanager:
    image: flink:1.6.4-scala_2.11
    ports:
      - '8081:8081'
      - '6123:6123'
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./volumes/common/conf/localtime:/etc/localtime:ro
      - ./volumes/common/conf/timezone:/etc/timezone:ro
      - ./volumes/flink/conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ../flinkStreamSQL:/opt/flinkStreamSQL
      - ./flinkjob:/opt/job

  taskmanager:
    image:  flink:1.6.4-scala_2.11
    expose:
      - '6121'
      - '6122'
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - 'jobmanager:jobmanager'
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./volumes/common/conf/localtime:/etc/localtime:ro
      - ./volumes/common/conf/timezone:/etc/timezone:ro
      - ./volumes/flink/conf/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ../flinkStreamSQL:/opt/flinkStreamSQL

flink-conf.yaml

jobmanager.rpc.address: jobmanager
jobmanager.rpc.port: 6123
jobmanager.heap.size: 512m
taskmanager.heap.size: 512m
taskmanager.numberOfTaskSlots: 1
parallelism.default: 1
rest.port: 8081
blob.server.port: 6124
query.server.port: 6125

@yangsishu @zoudaokoulife

**Comment by xinpiannanhai** [comment]
我也遇到一样的错误，standalone找不到集群

**Comment by tonychen0716** [comment]
我该用blink了，很多功能blink已经带了。

**Comment by xuelvming** [comment]
这个问题还是存在的啊，怎么就关掉了。

**Comment by ssyue** [comment]
@tonychen0716 这个解决了吗

**Comment by jianghanfen** [comment]
@tonychen0716 怎么解决？
