### ISSUE TITLE
自定义udaf 异常 Exception in thread "main" java.lang.RuntimeException: register UDF exception

### ISSUE THREAD

**Issue by lzhzu07** [DTStack/flinkStreamSQL#94]
写了一个udaf，通过tableEnvironment注册使用时没问题，用flinkStreamSQL addjar 注册时，会抛异常 Exception in thread "main" java.lang.RuntimeException: register UDF exception:class com.func.udaf.Avg。请问flinkStreamSQL支持这种方式添加自定义udaf吗？谢谢

**Comment by yangsishu** [comment]
有完整的错误信息吗

**Comment by lzhzu07** [comment]
异常信息：

Exception in thread "main" java.lang.RuntimeException: register UDF exception:class com.nwd.flink.func.udaf.Avg
	at com.dtstack.flink.sql.util.FlinkUtil.registerScalaUDF(FlinkUtil.java:188)
	at com.dtstack.flink.sql.util.FlinkUtil.registerUDF(FlinkUtil.java:159)
	at com.dtstack.flink.sql.Main.registerUDF(Main.java:263)
	at com.dtstack.flink.sql.Main.main(Main.java:169)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:72)

**Comment by lzhzu07** [comment]
udaf
Avg.scala
[Avg.scala.txt](https://github.com/DTStack/flinkStreamSQL/files/3011843/Avg.scala.txt)


sql：
[test.sql.txt](https://github.com/DTStack/flinkStreamSQL/files/3011839/test.sql.txt)

LauncherMain参数：
-sql E:\xxx\external-jar-sql.txt
-addjar "[\"E:\\xxx\\original-customfunc-1.0.jar\"]"
-name flinktest
-localSqlPluginPath E:\xxx\plugins
-mode local
-confProp {}

**Comment by yangsishu** [comment]
现在暂时不支持udaf
