### ISSUE TITLE
Flink1.7 提交任务空指针异常 Implementation error: Unhandled exception. java.lang.NullPointerException

### ISSUE THREAD

**Issue by 2efPer** [DTStack/flinkStreamSQL#97]
不知道是否是兼容性问题

> 2019-03-27 17:43:34,739 ERROR org.apache.flink.runtime.rest.handler.job.JobSubmitHandler    - Implementation error: Unhandled exception.
java.lang.NullPointerException
        at org.apache.flink.runtime.jobgraph.JobGraph.writeUserArtifactEntriesToConfiguration(JobGraph.java:586)
        at org.apache.flink.runtime.client.ClientUtils.setUserArtifactBlobKeys(ClientUtils.java:140)
        at org.apache.flink.runtime.client.ClientUtils.uploadAndSetUserArtifacts(ClientUtils.java:121)
        at org.apache.flink.runtime.client.ClientUtils.uploadJobGraphFiles(ClientUtils.java:78)
        at org.apache.flink.runtime.rest.handler.job.JobSubmitHandler.lambda$uploadJobGraphFiles$4(JobSubmitHandler.java:168)
        at java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1105)
        at java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1070)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by 2efPer** [comment]
呃，发现这是一个flink的陈年bug ：[FLINK-9974](https://issues.apache.org/jira/browse/FLINK-9974)

**Comment by 2efPer** [comment]
确实是兼容性的问题

**Comment by yangsishu** [comment]
1.7的分支才是支持flink1.7
